---
title: "Create Giotto object lung data - AL4 GATA3 Th cells"
author: "Sandy Kroh"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    number_sections: yes
    fig_caption: yes
    keep_md: yes
  pdf_document:
    toc: yes
params:
  Sample: Default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
if (!requireNamespace("Giotto", quietly = TRUE))
  devtools::install_github("drieslab/Giotto@suite")
library(Giotto)
library(ggplot2)
library(ggpubr)
```

## Directories

```{r}
output_dir <- here::here("1_spatial_setup", "import_Giotto_Lung_AL4_files")
dir.create(output_dir)

```

# Configuring Giotto package and raw data

Checking if miniconda and python is in place:

```{r}
# configure Giotto
genv_exists = checkGiottoEnvironment()
print(genv_exists)
if(!genv_exists){
  # The following command need only be run once to install the Giotto environment.
  installGiottoEnvironment()
}
```

## Import raw data

Load data frame with annotated cell types:

```{r}
datax <- read.csv(paste0(here::here(), "/data/MELC_data_murine_lung_CTRL_D1_D2_D3_withfolders.csv"))


```

## Data prep

We will separate different Th subpopulations by thresholding:

```{r fig.width=12, fig.height=4}
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggridges)

# 1. Define the target cell types and markers
target_types <- c("T helper cells", "T cytotox cells", "ILC2s", "ILC3s", "NK cells/ILC1s")
target_markers <- c("EOMES", "TBET", "GATA3eGFP", "RORgt", "CD4", "CD8a", "CD3")

# 2. Process the data
plot_data <- datax %>%
  # Filter for the specific cell types in AL3
  filter(AL3 %in% target_types) %>%
  # Select only the metadata and the markers of interest
  select(AL3, all_of(target_markers)) %>%
  # Pivot to long format: this puts all marker names in one column 
  # and all expression values in another, which is required for ridgeplots
  pivot_longer(cols = all_of(target_markers), 
               names_to = "Marker", 
               values_to = "Expression")

# 3. Create the Ridgeplot
ggplot(plot_data, aes(x = Expression, y = Marker, fill = AL3)) +
  geom_density_ridges(alpha = 0.7, scale = 1.5, rel_min_height = 0.01) +
  # You can facet by Marker or by Cell Type depending on how you want to compare
  facet_wrap(~ AL3, ncol = 5) + 
  theme_ridges() +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold", size = 10),
    axis.title.x = element_text(hjust = 0.5),
    axis.title.y = element_text(hjust = 0.5)
  ) +
  labs(
    title = "Marker Expression Profiles by Cell Type (AL3)",
    x = "Expression Intensity",
    y = "Protein Marker"
  ) +
  # Optional: use a nice color palette
  scale_fill_viridis_d(option = "D")
```

```{r}
library(dplyr)

datax <- datax %>%
  mutate(AL4 = case_when(
    # --- T Helper Cell Logic ---
    AL3 == "T helper cells" & GATA3eGFP > 1.5 ~ "Th2",
    AL3 == "T helper cells" & RORgt > 1.5     ~ "Th17",
    AL3 == "T helper cells" & TBET > 1      ~ "Th1",
    AL3 == "T helper cells"                  ~ "Other Th",
    
    # --- T Cytotox Cell Logic ---
    AL3 == "T cytotox cells" & GATA3eGFP > 1.5 ~ "Tc2",
    AL3 == "T cytotox cells"                   ~ "Other Tc",
    
    # --- All other cells (Retain original AL3 label) ---
    TRUE ~ as.character(AL3)
  ))

# define AL2 as Celltypes and inspect cell types
datax$CellType <- datax$AL4

datax$CellType <- gsub("EMCN CD31 |LYVE1 CD90 |lasma", "", datax$CellType)
unique(datax$CellType)
```

## Giotto

```{r}
samples <- unique(datax$FullInfo)
samples <- samples[!samples %in% "20210906_FOV3_D3"]
gio_list <- NULL
for(samp in samples){

  # cur_datax
  cur_datax <- datax[datax$FullInfo == samp,]

  # sample and image folder
  image_folder <- unique(cur_datax$Sample)
  print(image_folder)

  # data
  cur_data <- cur_datax[,2:34]
  rownames(cur_data) <- cur_datax$CellID
  cur_data <- t(cur_data)

  # metadata
  cur_metadata <- cur_datax[,38:46]
  rownames(cur_metadata) <- cur_datax$CellID

  # coordinates
  cur_coords <- cur_datax[,c("Loc_X", "Loc_Y")]
  rownames(cur_coords) <- cur_datax$CellID

  # main giotto object
  gio_list[[image_folder]] <- createGiottoObject(expression = cur_data, spatial_locs = cur_coords)

  # metadata
  gio_list[[image_folder]] <- addCellMetadata(gobject =  gio_list[[image_folder]], new_metadata = cur_metadata)

  # make delaunay graph
  gio_list[[image_folder]] <- createSpatialDelaunayNetwork(gio_list[[image_folder]])
}

```

## Visualization

Visualization of Giotto objects

```{r}
for (variable in 1:length(samples)) {
  print(spatPlot2D(gio_list[[variable]], cell_color = "CellType", point_size = 1)+
          ggtitle(names(gio_list[variable])))
}
```

# Save data

## Session information

```{r}
saveRDS(gio_list, file = paste0(output_dir, "/Giotto_data_lung_AL4.rds"))
save.image(paste0(output_dir, "/environment.RData"))
sessionInfo()
```
