---
title: "Lung and SI data"
author: "Sandy Kroh"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    number_sections: yes
    fig_caption: yes
    keep_md: yes
  pdf_document:
    toc: yes
params:
  Sample: Default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", 
                      fig.align='center', dpi = 600, 
                      message = FALSE, warning = FALSE)
options(width = 1200)
```

## Libraries

```{r}
library(moments)
library(rstatix)
library(Seurat)
library(SeuratObject)
library(dplyr)
library(ggplot2)
library(here)
library(ggbeeswarm)
library(ggpubr)
# library(stringr)
# library(glue)
# library(here)
library(readr)
# library(lubridate)
# library(data.table)
# library(clustree)
# library(magrittr)
# library(ggpubr)
# library(ggrepel)
# library(readxl)
# library(openxlsx)
```

## Parameters

```{r}
set.seed(123)

input_dir <- here::here("data")

output_dir <- here::here("1_data_tidying", "Lung_SI_all_cells_all_ALs_files")
dir.create(output_dir)




main_markers <- c(
  "EpCAM", "EMCN", "LYVE1", "PDPN", "PDGFRa", "CD8a", "CD4",
  "CD45", "CD3", "IRF4", "Kappa", "CD11c", "CD127", "GATA3eGFP", "RORgt"
)

immune_markers <- c(
 "CD3", "CD4", "CD8a", "Kappa", "IRF4", "CD11c",
  "CD127", "CD90", "EOMES", "GATA3eGFP", "RORgt", "Ki67",  "KLRG1", "NKp46", "CD117", "Areg", "CCR6", "CD44", "MHCII", "Sca1"
)

ilc_markers <- c(
  "CD3", "CD4", "CD8a",
  "CD127", "CD90", "EOMES", "GATA3eGFP", "RORgt", "KLRG1", "NKp46", "CD117", "CCR6", "MHCII", "Ki67", "Areg", "IRF4", "Sca1", "CD44"
)


cols_nat <- c("magenta", "cyan", "blue", "purple", "green", 
                       "red", "yellow", "olivedrab1", "slateblue1", 
                       "darkcyan", "gold","indianred1", "seagreen", "deeppink", 
                       "orange", "brown", "violet",
                       "deeppink4", "pink", 
                       "grey", "black", "lightgreen", 
                       "#FF0066",  
                       "lightblue", "#FFCC99", "#CC00FF", 
                       "blueviolet",  "goldenrod4", 
                       "navy", "olivedrab", "lightcyan", "seagreen2", "darkviolet", "lightpink", "slateblue4", "olivedrab2")

colfunc <- colorRampPalette(c("darkcyan", "green", "yellow", "magenta", "purple"))

```

# Load data

## SI

```{r, fig.width=9, fig.height=6}

SO.si <- readRDS(paste0(input_dir, "/SO_arcsinh_si_imputed__allALs_allCells.rds"))

SO.si@meta.data$Tissue.area <- gsub("Crypts", "Villi", SO.si@meta.data$Tissue.area)
SO.si <- subset(SO.si, subset = AL2 != "Unresolved")
# SO.villi <- subset(SO.si, subset = Tissue.area == "Villi")

```

Combine Mesenchymal cells I with Fibroblasts and rename mesenchymal cells II

```{r}
SO.si$AL2 <- gsub("Epithelia", "Epithelia I" , SO.si$AL2)
SO.si$AL3 <- gsub("Epithelia", "Epithelia I" , SO.si$AL3)

SO.si$AL2 <- gsub("Mesenchymal stromal cells II", "Epithelia II" , SO.si$AL2)
SO.si$AL3 <- gsub("Mesenchymal stromal cells II", "Epithelia II" , SO.si$AL3)

SO.si$AL2 <- gsub("Mesenchymal stromal cells I", "Fibroblasts" , SO.si$AL2)
SO.si$AL3 <- gsub("Mesenchymal stromal cells I", "Fibroblasts" , SO.si$AL3)

SO.si$AL1 <- gsub("Epithelia & stroma", "Epithelia" , SO.si$AL1)

df_si <- FetchData(SO.si, c(
  "nCount_MELC",
  "nFeature_MELC",
  "Location_Center_X",
  "Location_Center_Y",
  "Treatment",
  "FOV",
  "Experiment",
  "Organ",
  "MELC.machine",
  "Tissue.area",
  "Dataset",
  "CellID",
  "AL1",
  "AL2",
  "AL3",
  nrow(SO.si)
))

# adapt order
df_si$AL1 <- factor(df_si$AL1, c(
  "Immune cells", "Vessels & stroma", "Epithelia"
))

df_si$AL2 <- factor(df_si$AL2, c(
  "ILCs",
  "CD8+ CD3- IEL",
  "T helper cells",
  "T cytotox. cells",
  "Myeloid cells",
  "B cells",
  "Plasma cells",
  "Fibroblasts",
  "Blood vessels",
  "Lymphatics",
  "Epithelia I",
  "Epithelia II"
))

df_si$AL3 <- factor(df_si$AL3, c(
  "ILC2s",
  "NK cells/ILC1s/ILC3s",
  "CD8+ CD3- IEL",
  "T helper cells",
  "T cytotox. cells",
  "Myeloid cells",
  "B cells",
  "Plasma cells",
  "Fibroblasts",
  "Blood vessels",
  "Lymphatics",
  "Epithelia I",
  "Epithelia II"
))

```

### SI villi

Quantification proportions

```{r}

# info of AL is in long format
df_al1 <- df_si %>%
  reshape2::dcast(., Treatment + Dataset + Tissue.area ~ AL1) %>%
  mutate(TotalCellCountFOV = `Immune cells`+ `Vessels & stroma` + `Epithelia`) %>%
  select(Dataset, Treatment, Tissue.area, TotalCellCountFOV, 
         `Immune cells`, `Vessels & stroma`, `Epithelia`) %>%
  as.data.frame()


df_al2 <- df_si %>%
  reshape2::dcast(., Dataset ~ AL2) %>%
  as.data.frame()


df_al3 <- df_si %>%
  reshape2::dcast(., Dataset ~ AL3)%>%
  select(Dataset, `ILC2s`, `NK cells/ILC1s/ILC3s`) %>%
  as.data.frame()

# combine all ALs together
df_al <- merge(df_al1, df_al2, by = "Dataset")
df_al <- merge(df_al, df_al3, by = "Dataset")

# Treatment
df_al$Treatment <- factor(df_al$Treatment, 
                              levels = c("CTRL", "1", "3"))

# Convert to numeric
df_al[, c(4:length(colnames(df_al)))] <- lapply(df_al[, c(4:length(colnames(df_al)))], as.numeric)

# Check right formats
head(df_al)


```

```{r}

# Proportion of total cell count per FOV
for (element in c(colnames(df_al)[5:length(colnames(df_al))])) {
  number <- paste0("Prop_", element, "_perTotalCountFOV")
  df_al[number] <- round(df_al[element]/df_al["TotalCellCountFOV"]*100, 1)
}

# Proportion of total immune count per FOV
for (element in c(colnames(df_al)[8:14])) {
  number <- paste0("Prop_", element, "_perTotalImmuneFOV")
  df_al[number] <- round(df_al[element]/df_al["Immune cells"]*100, 1)
}
round(rowSums(df_al[39:length(colnames(df_al))], na.rm = TRUE), 0)

# Proportion of total immune count per FOV
for (element in c(colnames(df_al)[20:21])) {
  number <- paste0("Prop_", element, "_perTotalImmuneFOV")
  df_al[number] <- round(df_al[element]/df_al["Immune cells"]*100, 1)
}

# Proportion of total ILC count per FOV
for (element in c(colnames(df_al)[20:21])) {
  number <- paste0("Prop_", element, "_perTotalILCsFOV")
  df_al[number] <- round(df_al[element]/df_al["ILCs"]*100, 1)
}
round(rowSums(df_al[48:49], na.rm = TRUE), 0)

colnames(df_al)
```

Separate by tissue area:

```{r}

# separate by tissue area
df_villi <- df_al %>%
  filter(Tissue.area == "Villi")
df_ilf <- df_al %>%
  filter(Tissue.area == "ILF")
```

## Lung

```{r, fig.width=9, fig.height=6}

df <- read_csv(paste0(input_dir, "/20230808_SO_33M_arcsinh_lung_0.04_imputed_quantification_all_cells.csv"), 
    col_types = cols(...1 = col_skip()))

colnames(df) <- gsub("annotation_lvl", "AL", colnames(df))
df$AL3 <- gsub("EMCN CD31 ", "", df$AL3)
df$AL3 <- gsub("LYVE1 CD90 ", "", df$AL3)

CellIDs <- rownames(df)
# 2 TRANSPOSE DF -----
markers <- colnames(df)[12:43]
df_markers <- df %>%
  select(markers)
df_markers <- sapply(df_markers, as.numeric)
df_t <- t(df_markers)
colnames(df_t) <- CellIDs 
df_meta <- df %>%
  select(-markers) 
rownames(df_meta) <- CellIDs 
df_meta$Experiment <- as.factor(df_meta$Experiment)
df_meta$Dataset <- as.factor(df_meta$Dataset)
df_meta$CellID <- as.numeric(df_meta$CellID)
df_meta$Location_Center_X <- as.numeric(df_meta$Location_Center_X)
df_meta$Location_Center_Y <- as.numeric(df_meta$Location_Center_Y)
df_meta$UMAP_1 <- as.numeric(df_meta$UMAP_1)
df_meta$UMAP_2 <- as.numeric(df_meta$UMAP_2)
df_meta$AL1 <- as.factor(df_meta$AL1)
df_meta$AL2 <- as.factor(df_meta$AL2)
df_meta$AL3 <- as.factor(df_meta$AL3)
df_meta$AL4 <- as.factor(df_meta$AL4)

df_meta$max_features <- NULL

SO.lung <- CreateSeuratObject(
  counts = df_t,
  assay = "MELC",
  names.field = 0,
  names.delim = "_",
  meta.data = df_meta,
  project = "SeuratProject"
)


SO.lung@meta.data$AL3 <- factor(SO.lung@meta.data$AL3, levels = c(
  "NK cells/ILC1s", 
  "ILC2s", 
  "ILC3s", 
  "T helper cells", 
  "T cytotox cells", 
  "B cells & Plasma cells", 
  "Myeloid cells", 
  "Blood vessels", 
  "Lymphatics", 
  "LYVE1 CD31 vessels", 
  "Epithelia"
))

new.cluster.ids <- SO.lung@meta.data$AL3


```

Quantification

```{r}
df_lung <- read_csv(here::here("data", "20230808_SO_33M_arcsinh_lung_0.04_imputed_quantification_all_ALs_counts.csv"), 
    col_types = cols(...1 = col_skip()))

# Tidying
df_lung <- df_lung %>% 
  rename(`Endothelial blood cells` = `EMCN CD31 Blood vessels`, 
         `Endothelia & stroma` = `Vessels`, 
         `Lymphatics` = `LYVE1 CD90 Lymphatics`) %>%
  select(-c(`ILC2s A`, `ILC2s B`))

# AL1
for (element in c(colnames(df_lung)[6:8])) {
  number <- paste0("Prop_", element, "_perTotalCountFOV")
  df_lung[number] <- round(df_lung[element]/df_lung["TotalCellCountFOV"]*100, 1)
}
round(rowSums(df_lung[20:22], na.rm = TRUE), 0)

# AL2
for (element in c(colnames(df_lung)[12:19])) {
  number <- paste0("Prop_", element, "_perTotalImmuneFOV")
  df_lung[number] <- round(df_lung[element]/df_lung["Immune cells"]*100, 1)
}
round(rowSums(df_lung[23:27], na.rm = TRUE), 0)

# AL3
for (element in c(colnames(df_lung)[17:19])) {
  number <- paste0("Prop_", element, "_perTotalILCsFOV")
  df_lung[number] <- round(df_lung[element]/df_lung["ILCs"]*100, 1)
}
round(rowSums(df_lung[31:33], na.rm = TRUE), 0)


df_lung$`Tissue area` <- "Lung"
df_lung$Organ <- "Lung"

head(df_lung)
unique(df_lung$`Tissue area`)
df_lung[, c(1:4)] <- lapply(df_lung[, c(1:4)], as.character)

nrow(df_lung)

colnames(df_lung)
```

Visualize frequencies:

```{r, fig.height=6, fig.width=9}
df_freq <- df_lung %>%
  select(1, 4, 23:30)

# frequency of myeloid cells at different conditions -----------------------------
df_plot <-   df_freq %>%
  select(Dataset, Treatment, `Prop_Myeloid cells_perTotalImmuneFOV`) %>%
  mutate(Condition = Treatment, 
         value = `Prop_Myeloid cells_perTotalImmuneFOV`, 
         Condition = factor(Condition, levels = c(
           "CTRL", "1", "2", "3"
         )))

# Testing for normal distribution
shapiro.test(df_plot$value)
moments::kurtosis(df_plot$value)
moments::jarque.test(df_plot$value)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df_plot %>% kruskal_test(`value` ~ Condition)
res.kruskal
df_plot %>% kruskal_effsize(`value` ~ Condition)

# Pairwise comparisons using Dunn's test
pwc <- df_plot %>% 
  dunn_test(`value` ~ Condition, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ Condition, data = df_plot))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "Condition")

ggplot(df_plot, aes(x = Condition, y = value, fill = "Condition"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Condition), size = 2, cex = 2)+
  scale_color_manual(values = cols_nat)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(angle = 30, 
                                   vjust = 1, size = 12, hjust = 1, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.13, y.position = 50) +
  xlab(NULL)+
  ylab("Frequency per FOV/Immune [%]")+
  scale_y_continuous(expand = c(0, 0), limits = c(15,70))+
  NoLegend()

df_plot %>%
  group_by(Condition) %>%
  summarise(median = median(value))

# total count of myeloid cells at different conditions -----------------------------
df_plot <-   df_lung %>%
  select(Dataset, Treatment, `Myeloid cells`) %>%
  mutate(Condition = Treatment, 
         value = `Myeloid cells`, 
         Condition = factor(Condition, levels = c(
           "CTRL", "1", "2", "3"
         )))

# Testing for normal distribution
shapiro.test(df_plot$value)
moments::kurtosis(df_plot$value)
moments::jarque.test(df_plot$value)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df_plot %>% kruskal_test(`value` ~ Condition)
res.kruskal
df_plot %>% kruskal_effsize(`value` ~ Condition)

# Pairwise comparisons using Dunn's test
pwc <- df_plot %>% 
  dunn_test(`value` ~ Condition, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ Condition, data = df_plot))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "Condition")

ggplot(df_plot, aes(x = Condition, y = value, fill = "Condition"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Condition), size = 2, cex = 2)+
  scale_color_manual(values = cols_nat)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(angle = 30, 
                                   vjust = 1, size = 12, hjust = 1, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.13, y.position = 50) +
  xlab(NULL)+
  ylab("Frequency per FOV/Immune [%]")+
  # scale_y_continuous(expand = c(0, 0), limits = c(15,70))+
  NoLegend()

df_plot %>%
  group_by(Condition) %>%
  summarise(median = median(value))


# frequency of different celltypes under homeostatic conditions -----------------
df_plot <-   df_freq %>%
  filter(Treatment == "CTRL") %>%
  tidyr::pivot_longer(cols = -c(Dataset, Treatment), names_to = "CellType") %>%
  mutate(CellType = gsub("Prop_|_perTotalImmuneFOV", "", CellType), 
         CellType = factor(CellType, levels = c(
           "ILCs",
           "NK cells/ILC1s",
           "ILC2s",
           "ILC3s",
           "Myeloid cells",
           "B cells & Plasma cells",
           "T cytotox cells",
           "T helper cells"
         ))
  )

# Testing for normal distribution
shapiro.test(df_plot$value)
moments::kurtosis(df_plot$value)
moments::jarque.test(df_plot$value)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df_plot %>% kruskal_test(`value` ~ CellType)
res.kruskal
df_plot %>% kruskal_effsize(`value` ~ CellType)

# Pairwise comparisons using Dunn's test
pwc <- df_plot %>% 
  dunn_test(`value` ~ CellType, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ CellType, data = df_plot))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "CellType")

ggplot(df_plot, aes(x = CellType, y = value, fill = "CellType"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = CellType), size = 2, cex = 2)+
  scale_color_manual(values = cols_nat)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(angle = 30, 
                                   vjust = 1, size = 12, hjust = 1, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.13, y.position = 40) +
  xlab(NULL)+
  ylab("Frequency per FOV/Immune [%]")+
  scale_y_continuous(expand = c(0, 0), limits = c(0,100))+
  NoLegend()



df_lung %>%
  select(Dataset, Treatment, `Myeloid cells`) %>%
  mutate(Condition = Treatment, 
         value = `Myeloid cells`, 
         Condition = factor(Condition, levels = c(
           "CTRL", "1", "2", "3"
         ))) %>%
  group_by(Condition) %>%
  summarise(median = median(value))


df_lung %>%
  select(Dataset, Treatment, `Myeloid cells`, TotalCellCountFOV) %>%
  mutate(Condition = Treatment, 
         value = `Myeloid cells`/TotalCellCountFOV*100, 
         Condition = factor(Condition, levels = c(
           "CTRL", "1", "2", "3"
         ))) %>%
  group_by(Condition) %>%
  summarise(median = median(value))

df_lung %>%
  select(Dataset, Treatment, `Myeloid cells`, `Immune cells`) %>%
  mutate(Condition = Treatment, 
         value = `Myeloid cells`/`Immune cells`*100, 
         Condition = factor(Condition, levels = c(
           "CTRL", "1", "2", "3"
         ))) %>%
  group_by(Condition) %>%
  summarise(median = median(value))

```

# Save data

## Session Information

```{r}
write.csv(df_lung, paste0(output_dir, "/lung_proportions.csv"))
write.csv(df_si, paste0(output_dir, "/si_all_cells_all_ALs.csv"))
write.csv(df_villi, paste0(output_dir, "/si_villi_proportions.csv"))
write.csv(df_ilf, paste0(output_dir, "/si_ilf_proportions.csv"))
saveRDS(SO.si, paste0(output_dir, "/si_all_cells_all_ALs.rds"))
saveRDS(SO.lung, paste0(output_dir, "/lung_all_cells_all_ALs.rds"))
save.image(paste0(output_dir, "/environment.RData"))
sessionInfo()
```
