---
title: "Figure 1: MELC panel and sample prep workflow"
author: "Sandy Kroh"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    fig_caption: yes
    keep_md: yes
  pdf_document:
    toc: yes
params:
  Sample: Default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", 
                      fig.align='center', dpi = 600, 
                      set.seed(8),
                      message = FALSE, warning = FALSE)
options(width = 1200)
```

## Libraries

```{r}
library(rlang)
library(dplyr)
library(png)
library(grid)
library(ggplot2)
library(ggpubr)

```

## Parameters

```{r}
set.seed(123)

input_dir <- here::here("data", "images")

output_dir <- here::here("2_visualizations_for_figures", "Fig_1_MELC_panel_workflow_files")
dir.create(output_dir)

```

# IF overlays

## MELC panel mosaic

```{r fig.height=6.9, fig.width=9}

# 1. Define the path
img_path <- paste0(input_dir, "/MELC_overview_lung.png")

# 2. Read the image and get dimensions
img <- readPNG(img_path)
h <- nrow(img)
w <- ncol(img)

# 3. Create the ggplot object
# We use coord_fixed to ensure the image doesn't stretch
img_plot_melc_panel <- ggplot() +
  annotation_raster(img, xmin = 0, xmax = w, ymin = 0, ymax = h) +
  coord_fixed() +
  theme_void() +
  # Optional: adds a tiny margin to ensure the edges aren't clipped
  scale_x_continuous(expand = c(0, 0), limits = c(0, w)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, h)) +
  theme(plot.margin = margin(0, 0, 0.7, 0.7, "cm"))

```

## IF ILC markers colocalization

```{r fig.height=6.5, fig.width=9}

# 1. Define the path
img_path <- paste0(input_dir, "/Colocalization_ILC_markers.png")

# 2. Read the image and get dimensions
img <- readPNG(img_path)
h <- nrow(img)
w <- ncol(img)

# 3. Create the ggplot object
# We use coord_fixed to ensure the image doesn't stretch
img_plot_coloc <- ggplot() +
  annotation_raster(img, xmin = 0, xmax = w, ymin = 0, ymax = h) +
  coord_fixed() +
  theme_void() +
  # Optional: adds a tiny margin to ensure the edges aren't clipped
  scale_x_continuous(expand = c(0, 0), limits = c(0, w)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, h)) +
  theme(plot.margin = margin(0, 0, 0, 0.7, "cm"))

```

## IF endothelial markers colocalization

```{r fig.height=8.2, fig.width=9}

# 1. Define the path
img_path <- paste0(input_dir, "/Colocalization_endothelial_markers.png")

# 2. Read the image and get dimensions
img <- readPNG(img_path)
h <- nrow(img)
w <- ncol(img)

# 3. Create the ggplot object
# We use coord_fixed to ensure the image doesn't stretch
img_plot_coloc_endo <- ggplot() +
  annotation_raster(img, xmin = 0, xmax = w, ymin = 0, ymax = h) +
  coord_fixed() +
  theme_void() +
  # Optional: adds a tiny margin to ensure the edges aren't clipped
  scale_x_continuous(expand = c(0, 0), limits = c(0, w)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, h)) +
  theme(plot.margin = margin(0, 0, 0, 0.7, "cm"))

```

## IF immune markers colocalization

```{r fig.height=4.9, fig.width=9}

# 1. Define the path
img_path <- paste0(input_dir, "/Colocalization_immune_markers.png")

# 2. Read the image and get dimensions
img <- readPNG(img_path)
h <- nrow(img)
w <- ncol(img)

# 3. Create the ggplot object
# We use coord_fixed to ensure the image doesn't stretch
img_plot_coloc_imm <- ggplot() +
  annotation_raster(img, xmin = 0, xmax = w, ymin = 0, ymax = h) +
  coord_fixed() +
  theme_void() +
  # Optional: adds a tiny margin to ensure the edges aren't clipped
  scale_x_continuous(expand = c(0, 0), limits = c(0, w)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, h)) +
  theme(plot.margin = margin(0, 0, 0, 0.7, "cm"))

```

## IF epithelial markers colocalization

```{r fig.height=3.7, fig.width=9}

# 1. Define the path
img_path <- paste0(input_dir, "/Colocalization_epithelial_markers.png")

# 2. Read the image and get dimensions
img <- readPNG(img_path)
h <- nrow(img)
w <- ncol(img)

# 3. Create the ggplot object
# We use coord_fixed to ensure the image doesn't stretch
img_plot_coloc_epi <- ggplot() +
  annotation_raster(img, xmin = 0, xmax = w, ymin = 0, ymax = h) +
  coord_fixed() +
  theme_void() +
  # Optional: adds a tiny margin to ensure the edges aren't clipped
  scale_x_continuous(expand = c(0, 0), limits = c(0, w)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, h)) +
  theme(plot.margin = margin(0, 0, 0, 0.7, "cm"))

```

## MELC workflow

```{r fig.height=6.2, fig.width=9}

# 1. Define the path
img_path <- paste0(input_dir, "/workflow_sample_prep@4x.png")

# 2. Read the image and get dimensions
img <- readPNG(img_path)
h <- nrow(img)
w <- ncol(img)

# 3. Create the ggplot object
# We use coord_fixed to ensure the image doesn't stretch
img_plot_workflow <- ggplot() +
  annotation_raster(img, xmin = 0, xmax = w, ymin = 0, ymax = h) +
  coord_fixed() +
  theme_void() +
  # Optional: adds a tiny margin to ensure the edges aren't clipped
  scale_x_continuous(expand = c(0, 0), limits = c(0, w)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, h)) +
  theme(plot.margin = margin(0, 0, 0, 0, "cm"))

```

# Visualization for figures

## Figure 1

```{r, fig.width=9, fig.height=13.4}
ggarrange(img_plot_melc_panel, img_plot_coloc, 
          nrow = 2, ncol = 1, 
          heights = c(6.9, 6.5), 
          labels = "AUTO")
```

## Supplementary Figures

```{r fig.height=6.2, fig.width=9}


# Display the plot
print(img_plot_workflow)
```

```{r, fig.width=9, fig.height=16.8}
ggarrange(img_plot_coloc_endo, img_plot_coloc_imm, img_plot_coloc_epi, 
          nrow = 3, ncol = 1, 
          heights = c(8.2, 4.9, 3.7), 
          labels = "AUTO")
```

## Session Information

```{r}
sessionInfo()
```
