---
title: "Figure 4: Quantification lung"
author: "Sandy Kroh"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    number_sections: yes
    fig_caption: yes
    keep_md: yes
  pdf_document:
    toc: yes
params:
  Sample: Default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", 
                      fig.align='center', dpi = 600, 
                      message = FALSE, warning = FALSE)
options(width = 1200)
```

## Libraries

```{r}
library(Seurat)
library(SeuratObject)
library(dplyr)
library(ggplot2)
library(rstatix)
library(ggbeeswarm)
# library(stringr)
# library(glue)
# library(here)
library(readr)
# library(lubridate)
# library(data.table)
# library(clustree)
# library(magrittr)
library(ggpubr)
# library(ggrepel)
# library(readxl)
# library(openxlsx)
```

## Parameters

```{r}
set.seed(123)

input_dir <- here::here("1_data_tidying", "Lung_SI_all_cells_all_ALs_files")

output_dir <- here::here("2_visualizations_for_figures", "Fig_4_quantification_lung_files")
dir.create(output_dir)




main_markers <- c(
  "EpCAM", "EMCN", "LYVE1", "PDPN", "PDGFRa", "CD8a", "CD4",
  "CD45", "CD3", "IRF4", "Kappa", "CD11c", "CD127", "GATA3eGFP", "RORgt"
)


immune_markers <- c(
 "CD3", "CD4", "CD8a", "Kappa", "IRF4", "CD11c",
  "CD127", "CD90", "EOMES", "GATA3eGFP", "RORgt", "Ki67",  "KLRG1", "NKp46", "CD117", "Areg", "CCR6", "CD44", "MHCII", "Sca1"
)

ilc_markers <- c(
  "CD3", "CD4", "CD8a",
  "CD127", "CD90", "EOMES", "GATA3eGFP", "RORgt", "KLRG1", "NKp46", "CD117", "CCR6", "MHCII", "Ki67", "Areg", "IRF4", "Sca1", "CD44"
)


cols_nat <- c("magenta", "cyan", "blue", "purple", "green", 
                       "red", "yellow", "olivedrab1", "slateblue1", 
                       "darkcyan", "gold","indianred1", "seagreen", "deeppink", 
                       "orange", "brown", "violet",
                       "deeppink4", "pink", 
                       "grey", "black", "lightgreen", 
                       "#FF0066",  
                       "lightblue", "#FFCC99", "#CC00FF", 
                       "blueviolet",  "goldenrod4", 
                       "navy", "olivedrab", "lightcyan", "seagreen2", "darkviolet", "lightpink", "slateblue4", "olivedrab2")

colfunc <- colorRampPalette(c("darkcyan", "green", "yellow", "magenta", "purple"))

cols_ilcs_lung <- c("darkcyan", "seagreen2", "deeppink4")

cols_treat <- c("darkcyan", "gold", "deeppink", "slateblue")

```

# Load data

```{r, fig.width=9, fig.height=6}

df_lung <- read_csv(paste0(input_dir, "/lung_proportions.csv"), 
    col_types = cols(...1 = col_skip()))

```

# Visualization

## Count of ILCs \@CTRL conditions

```{r, fig.width=3, fig.height=4}

# filter for CTRL and convert to longer format
df <- df_lung %>%
  filter(Treatment == "CTRL") %>%
  select(Treatment, Dataset, `NK cells/ILC1s`, ILC2s, ILC3s) %>%
  tidyr::pivot_longer(cols = c(`NK cells/ILC1s`, ILC2s, ILC3s), names_to = "ILCtype") %>%
  mutate(ILCtype = factor(ILCtype, level = c(
    "NK cells/ILC1s", "ILC2s", "ILC3s"
  )))

# Testing for normal distribution
shapiro.test(df$value)
moments::kurtosis(df$value)
moments::jarque.test(df$value)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df %>% kruskal_test(`value` ~ ILCtype)
res.kruskal
df %>% kruskal_effsize(`value` ~ ILCtype)

# Pairwise comparisons using Dunn's test
pwc <- df %>% 
  dunn_test(`value` ~ ILCtype, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ ILCtype, data = df))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "ILCtype")

plot_prop <- ggplot(df, aes(x = ILCtype, y = value, fill = "ILCtype"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = ILCtype), size = 2, cex = 3)+
  scale_color_manual(values = cols_ilcs_lung)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(angle = 30, 
                                   vjust = 1, size = 12, hjust = 1, face = "bold"),
         axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.1, y.position = 20) +
  xlab(NULL)+
  ylab("Count per FOV [#]")+
  scale_y_continuous(expand = c(0, 0), limits = c(0,24))+
    # annotate(geom = 'text',
    #        x="ILC2s",
    #        y=28,
    #        label=Labels[1], 
    #        #angle = 90, 
    #        size = 10/.pt)+
  NoLegend()

plot_prop

```

## Frequencies of ILCs within ILC compartment @ CTRL conditions

```{r, fig.width=3, fig.height=4}

# filter for CTRL and convert to longer format
df <- df_lung %>%
  filter(Treatment == "CTRL") %>%
  select(Treatment, Dataset, `Prop_NK cells/ILC1s_perTotalILCsFOV`, Prop_ILC2s_perTotalILCsFOV, Prop_ILC3s_perTotalILCsFOV) %>%
  tidyr::pivot_longer(cols = c(`Prop_NK cells/ILC1s_perTotalILCsFOV`, Prop_ILC2s_perTotalILCsFOV, Prop_ILC3s_perTotalILCsFOV), names_to = "ILCtype") %>%
  mutate(ILCtype = gsub("Prop_|_perTotalILCsFOV", "", ILCtype), 
         ILCtype = factor(ILCtype, level = c(
    "NK cells/ILC1s", "ILC2s", "ILC3s"
  )))

# Testing for normal distribution
shapiro.test(df$value)
moments::kurtosis(df$value)
moments::jarque.test(df$value)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df %>% kruskal_test(`value` ~ ILCtype)
res.kruskal
df %>% kruskal_effsize(`value` ~ ILCtype)

# Pairwise comparisons using Dunn's test
pwc <- df %>% 
  dunn_test(`value` ~ ILCtype, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ ILCtype, data = df))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "ILCtype")

plot_freq <- ggplot(df, aes(x = ILCtype, y = value, fill = "ILCtype"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = ILCtype), size = 2, cex = 3)+
  scale_color_manual(values = cols_ilcs_lung)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(angle = 30, 
                                   vjust = 1, size = 12, hjust = 1, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.1, y.position = 90) +
  xlab(NULL)+
  ylab("Frequency per FOV/ILCs [%]")+
  scale_y_continuous(expand = c(0, 0), limits = c(0,105))+
  NoLegend()


plot_freq
```

## Frequency of ILCs within immune compartment @ CTRL

```{r, fig.width=3, fig.height=4}

# filter for CTRL and convert to longer format
df <- df_lung %>%
  filter(Treatment == "CTRL") %>%
  select(Treatment, Dataset, `Prop_NK cells/ILC1s_perTotalImmuneFOV`, Prop_ILC2s_perTotalImmuneFOV, Prop_ILC3s_perTotalImmuneFOV) %>%
  tidyr::pivot_longer(cols = c(`Prop_NK cells/ILC1s_perTotalImmuneFOV`, Prop_ILC2s_perTotalImmuneFOV, Prop_ILC3s_perTotalImmuneFOV), names_to = "ILCtype") %>%
  mutate(ILCtype = gsub("Prop_|_perTotalImmuneFOV", "", ILCtype), 
         ILCtype = factor(ILCtype, level = c(
    "NK cells/ILC1s", "ILC2s", "ILC3s"
  )))

# Testing for normal distribution
shapiro.test(df$value)
moments::kurtosis(df$value)
moments::jarque.test(df$value)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df %>% kruskal_test(`value` ~ ILCtype)
res.kruskal
df %>% kruskal_effsize(`value` ~ ILCtype)

# Pairwise comparisons using Dunn's test
pwc <- df %>% 
  dunn_test(`value` ~ ILCtype, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ ILCtype, data = df))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "ILCtype")

plot_freq_immune <- ggplot(df, aes(x = ILCtype, y = value, fill = "ILCtype"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = ILCtype), size = 2, cex = 3)+
  scale_color_manual(values = cols_ilcs_lung)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(angle = 30, 
                                   vjust = 1, size = 12, hjust = 1, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.1, y.position = 11) +
  xlab(NULL)+
  ylab("Frequency per FOV/Immune [%]")+
  scale_y_continuous(expand = c(0, 0), limits = c(0,14))+
  NoLegend()

plot_freq_immune
```

## Total cell count IL-33

```{r, fig.width=3, fig.height=3}

# filter for CTRL and convert to longer format
df <- df_lung %>%
  select(Treatment, Dataset, TotalCellCountFOV) %>%
  mutate(Treatment = factor(Treatment, level =c(
    "CTRL", "1", "2", "3"
  )))

# Testing for normal distribution
shapiro.test(df$TotalCellCountFOV)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df %>% kruskal_test(`TotalCellCountFOV` ~ Treatment)
res.kruskal
df %>% kruskal_effsize(`TotalCellCountFOV` ~ Treatment)

# Pairwise comparisons using Dunn's test
pwc <- df %>% 
  dunn_test(`TotalCellCountFOV` ~ Treatment, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ Treatment, data = df))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "Treatment")

plot_count_all <- ggplot(df, aes(x = Treatment, y = TotalCellCountFOV, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(#angle = 45, 
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
         axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.1, y.position = 5200) +
  xlab(NULL)+
  ylab("Total count per FOV [#]")+
  ggtitle("Total cells")+
  scale_y_continuous(expand = c(0, 0), limits = c(0,6800))+
  NoLegend()
# +
#     annotate(geom = 'text',
#            x="ILC2s",
#            y=28,
#            label=Labels[1], 
#            #angle = 90, 
#            size = 10/.pt)

plot_count_all
```

## Total immune count IL-33

```{r, fig.width=3, fig.height=3}

# filter for CTRL and convert to longer format
df <- df_lung %>%
  select(Treatment, Dataset, `Immune cells`) %>%
  mutate(Treatment = factor(Treatment, level =c(
    "CTRL", "1", "2", "3"
  )))

# Testing for normal distribution
shapiro.test(df$`Immune cells`)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df %>% kruskal_test(`Immune cells` ~ Treatment)
res.kruskal
df %>% kruskal_effsize(`Immune cells` ~ Treatment)

# Pairwise comparisons using Dunn's test
pwc <- df %>% 
  dunn_test(`Immune cells` ~ Treatment, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ Treatment, data = df))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "Treatment")

plot_count_immune <- ggplot(df, aes(x = Treatment, y = `Immune cells`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(#angle = 45, 
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
         axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.1, y.position = 1750) +
  xlab(NULL)+
  ylab("Total count per FOV [#]")+
  ggtitle("Immune cells")+
  scale_y_continuous(expand = c(0, 0), limits = c(0,2300))+
  NoLegend()
# +
#     annotate(geom = 'text',
#            x="ILC2s",
#            y=28,
#            label=Labels[1], 
#            #angle = 90, 
#            size = 10/.pt)

plot_count_immune
```

## Total ILC count IL-33

```{r, fig.width=3, fig.height=3}

# filter for CTRL and convert to longer format
df <- df_lung %>%
  select(Treatment, Dataset, ILCs) %>%
  mutate(Treatment = factor(Treatment, level =c(
    "CTRL", "1", "2", "3"
  )))

# Testing for normal distribution
shapiro.test(df$ILCs)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df %>% kruskal_test(`ILCs` ~ Treatment)
res.kruskal
df %>% kruskal_effsize(`ILCs` ~ Treatment)

# Pairwise comparisons using Dunn's test
pwc <- df %>% 
  dunn_test(`ILCs` ~ Treatment, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ Treatment, data = df))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "Treatment")

plot_count_ilc <- ggplot(df, aes(x = Treatment, y = ILCs, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(#angle = 45, 
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
         axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.08, y.position = 80) +
  xlab(NULL)+
  ylab("Total count per FOV [#]")+
  ggtitle("ILCs")+
  scale_y_continuous(expand = c(0, 0), limits = c(0,100))+
  NoLegend()
# +
#     annotate(geom = 'text',
#            x="ILC2s",
#            y=28,
#            label=Labels[1], 
#            #angle = 90, 
#            size = 10/.pt)

plot_count_ilc
```

## Total count ILC1s/NK cells

```{r, fig.width=3, fig.height=3}

# filter for CTRL and convert to longer format
df <- df_lung %>%
  select(Treatment, Dataset, `NK cells/ILC1s`) %>%
  mutate(Treatment = factor(Treatment, level =c(
    "CTRL", "1", "2", "3"
  )))

# Testing for normal distribution
shapiro.test(df$`NK cells/ILC1s`)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df %>% kruskal_test(`NK cells/ILC1s` ~ Treatment)
res.kruskal
df %>% kruskal_effsize(`NK cells/ILC1s` ~ Treatment)

# Pairwise comparisons using Dunn's test
pwc <- df %>% 
  dunn_test(`NK cells/ILC1s` ~ Treatment, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ Treatment, data = df))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "Treatment")

plot_count_ilc1 <- ggplot(df, aes(x = Treatment, y = `NK cells/ILC1s`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(#angle = 45, 
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
         axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.1, y.position = 65) +
  xlab(NULL)+
  ylab("Total count per FOV [#]")+
  ggtitle("NK cells/ILC1s")+
  scale_y_continuous(expand = c(0, 0), limits = c(0,78))+
  NoLegend()
# +
#     annotate(geom = 'text',
#            x="ILC2s",
#            y=28,
#            label=Labels[1], 
#            #angle = 90, 
#            size = 10/.pt)

plot_count_ilc1
```

## Total count ILC2s

```{r, fig.width=3, fig.height=4}

# filter for CTRL and convert to longer format
df <- df_lung %>%
  select(Treatment, Dataset, `ILC2s`) %>%
  mutate(Treatment = factor(Treatment, level =c(
    "CTRL", "1", "2", "3"
  )))

# Testing for normal distribution
shapiro.test(df$`ILC2s`)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df %>% kruskal_test(`ILC2s` ~ Treatment)
res.kruskal
df %>% kruskal_effsize(`ILC2s` ~ Treatment)

# Pairwise comparisons using Dunn's test
pwc <- df %>% 
  dunn_test(`ILC2s` ~ Treatment, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ Treatment, data = df))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "Treatment")

plot_count_ilc2 <- ggplot(df, aes(x = Treatment, y = `ILC2s`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(#angle = 45, 
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
         axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.1, y.position = 158) +
  xlab(NULL)+
  ylab("Total count per FOV [#]")+
  ggtitle("ILC2s")+
  scale_y_continuous(expand = c(0, 0), limits = c(0,190))+
  NoLegend()
# +
#     annotate(geom = 'text',
#            x="ILC2s",
#            y=28,
#            label=Labels[1], 
#            #angle = 90, 
#            size = 10/.pt)

plot_count_ilc2
```

## Total count ILC3s

```{r, fig.width=3, fig.height=4}

# filter for CTRL and convert to longer format
df <- df_lung %>%
  select(Treatment, Dataset, `ILC3s`) %>%
  mutate(Treatment = factor(Treatment, level =c(
    "CTRL", "1", "2", "3"
  )))

# Testing for normal distribution
shapiro.test(df$`ILC3s`)

# Kruskal-Wallis-test to check for significance between tested groups and effect size
res.kruskal <- df %>% kruskal_test(`ILC3s` ~ Treatment)
res.kruskal
df %>% kruskal_effsize(`ILC3s` ~ Treatment)

# Pairwise comparisons using Dunn's test
pwc <- df %>% 
  dunn_test(`ILC3s` ~ Treatment, p.adjust.method = "bonferroni") 
pwc

# add N to plot
tab <- data.frame(xtabs(~ Treatment, data = df))
head(tab)
# Add cell number per cluster to cluster labels
Labels = paste0("n = ", tab$Freq, "")



# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "Treatment")

plot_count_ilc3 <- ggplot(df, aes(x = Treatment, y = `ILC3s`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(plot.margin=margin(1,0.5,1,1,"cm"),
        axis.text.x = element_text(#angle = 45, 
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
         axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  stat_pvalue_manual(pwc,
                       hide.ns = TRUE, size = 6,
                       step.increase = 0.1, y.position = 11) +
  xlab(NULL)+
  ylab("Total count per FOV [#]")+
  ggtitle("ILC3s")+
  scale_y_continuous(expand = c(0, 0), limits = c(0,14))+
  NoLegend()
# +
#     annotate(geom = 'text',
#            x="ILC2s",
#            y=28,
#            label=Labels[1], 
#            #angle = 90, 
#            size = 10/.pt)

plot_count_ilc3
```

## 

## Combine plots for figure

```{r, fig.width=9, fig.height=9.5}
ggarrange(plot_prop, plot_freq_immune, plot_freq, 
          plot_count_all, plot_count_immune, plot_count_ilc, 
          plot_count_ilc1, plot_count_ilc2, plot_count_ilc3, 
          ncol = 3, nrow = 3, heights = c(3.5, 3, 3), 
          labels = c("A", "B", "C", "D", "E", "F", "G", "H", "I"))+
  theme(plot.margin = margin(0, 0.1, 0, 0, "cm"))
```

## Session Information

```{r}
save.image(paste0(output_dir, "/environment.RData"))
sessionInfo()
```
