---
title: "Figure 6: Spatial analysis of NK cells/ILC1s in lung"
author: "Sandy Kroh"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    number_sections: yes
    fig_caption: yes
    keep_md: yes
  pdf_document:
    toc: yes
params:
  Sample: Default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", 
                      fig.align='center', dpi = 600, 
                      message = FALSE, warning = FALSE)
options(width = 1200)
```

## Libraries

```{r}
library(SeuratObject)
library(dplyr)
library(rstatix)

# remove.packages("rlang")
# remove.packages("dplyr")
# install.packages("rlang")
# install.packages("dplyr")
library(rlang)
library(dplyr)

if (!requireNamespace("Giotto", quietly = TRUE))
  devtools::install_github("drieslab/Giotto@suite")
if (!requireNamespace("VoltRon", quietly = TRUE))
  devtools::install_github("Artur-man/VoltRon")
if (!requireNamespace("Seurat", quietly = TRUE))
  install.packages("Seurat")
library(Giotto)
library(Seurat)
library(VoltRon)
library(ggplot2)
library(ggpubr)
library(readr)
library(ggbeeswarm)
library(stringr)
```

## Parameters

```{r}
set.seed(123)

input_dir <- here::here("1_data_tidying", "Lung_SI_all_cells_all_ALs_files")

output_dir <- here::here("2_visualizations_for_figures", "Fig_6_spatial_analysis_NKcellsILC1s_lung_files")
dir.create(output_dir)




main_markers <- c(
  "EpCAM", "EMCN", "LYVE1", "PDPN", "PDGFRa", "CD8a", "CD4",
  "CD45", "CD3", "IRF4", "Kappa", "CD11c", "CD127", "GATA3eGFP", "RORgt"
)


immune_markers <- c(
 "CD3", "CD4", "CD8a", "Kappa", "IRF4", "CD11c",
  "CD127", "CD90", "EOMES", "GATA3eGFP", "RORgt", "Ki67",  "KLRG1", "NKp46", "CD117", "Areg", "CCR6", "CD44", "MHCII", "Sca1"
)

ilc_markers <- c(
  "CD3", "CD4", "CD8a",
  "CD127", "CD90", "EOMES", "GATA3eGFP", "RORgt", "KLRG1", "NKp46", "CD117", "CCR6", "MHCII", "Ki67", "Areg", "IRF4", "Sca1", "CD44"
)


cols_nat <- c("magenta", "cyan", "blue", "purple", "green", 
                       "red", "yellow", "olivedrab1", "slateblue1", 
                       "darkcyan", "gold","indianred1", "seagreen", "deeppink", 
                       "orange", "brown", "violet",
                       "deeppink4", "pink", 
                       "grey", "black", "lightgreen", 
                       "#FF0066",  
                       "lightblue", "#FFCC99", "#CC00FF", 
                       "blueviolet",  "goldenrod4", 
                       "navy", "olivedrab", "lightcyan", "seagreen2", "darkviolet", "lightpink", "slateblue4", "olivedrab2")

colfunc <- colorRampPalette(c("darkcyan", "green", "yellow", "magenta", "purple"))

cols_ilcs_lung <- c("darkcyan", "seagreen2", "deeppink4")

cols_treat <- c("darkcyan", "gold", "deeppink", "slateblue")

```

# Load data

```{r, fig.width=9, fig.height=6}

# from import_Giotto.Rmd
gio_list <- readRDS(here::here("data", "Giotto_data_lung.rds"))

# from import_VoltRon.Rmd
vr_list <- readRDS(here::here("data", "VoltRon_data_lung.rds"))

# original data
metadatax <- read_csv(here::here("data", "MELC_data_murine_lung_CTRL_D1_D2_D3_withfolders.csv"))
metadatax <- metadatax %>%
  mutate(CellType = AL3)  %>%
  filter(Sample != "20210906_3_lu_d3")

unique(metadatax$CellType)

vr_list_names <- unique(metadatax$Sample)


cell_proximities_list <- list()
for(samp in vr_list_names){
  print(samp)
  cell_proximities_list[[samp]] <-cellProximityEnrichment(
    gobject = gio_list[[samp]],
    cluster_column = 'CellType',
    spatial_network_name = 'Delaunay_network',
    adjust_method = 'fdr',
    number_of_simulations = 1000)
  cell_proximities_list[[samp]] <- cell_proximities_list[[samp]]$enrichm_res
}

vr_merged <- merge(vr_list[[1]], vr_list[-1])
vrImageNames(vr_merged)
unique(vr_merged$CellType)

```

Calculate co-enrichment scores and plot them:

```{r, fig.height=4, fig.width=9}

# FOVs for representative overview images
fovs <- vr_list_names

set_alpha <- 0.35
set_ptsize <- 2
set_nrows <- 1
set_ncols <- 3
cell_shape <- 20


cols_con <- c("darkcyan", "gold", "deeppink", 
                "slateblue")

cols_fov <- c("darkcyan", "gold", "deeppink", 
                "slateblue")

ColorsCellType <-  list(
  #`NK cells/ILC1s/ILC3s` = "cyan", 
  `NK cells/ILC1s` = "magenta",
  #`ILC3s` = "magenta", 
  `EMCN CD31 Blood vessels` = "green")

uni_celltypes <- unique(vr_merged$CellType)
backgroundlist <- list("EpCAM","CD31","LYVE1","LYVE1","CD11c","B220","EOMES", "CD8a", "CD4", "GATA3eGFP", "RORgt")
names(backgroundlist) <- uni_celltypes
uni_celltypes <- uni_celltypes[!uni_celltypes %in% "NK cells/ILC1s"]

g_master_list <- list()
for(unic in uni_celltypes){
  
    ### selected cell groups ####
  selected_celltypes <- c("NK cells/ILC1s", unic)
  # interactions <- c("EMCN CD31 Blood vessels--ILC2s")
  interactions <- unique(cell_proximities_list[[vr_list_names[30]]]$unified_int)
  interactions <- interactions[grepl("NK cells/ILC1s", interactions) & grepl(unic, interactions)]
  background_image <- backgroundlist[[unic]]
  if(length(interactions) > 0){
     ### get interaction results ####
    interaction_celltypes <- NULL
    for(samp in vr_list_names){
      cur_cell_proximities <- cell_proximities_list[[samp]]
      cur_cell_proximities <- cur_cell_proximities[cur_cell_proximities$unified_int %in% interactions,]
      sample <- unique(metadatax$FullInfo[metadatax$Sample==samp])
      if(nrow(cur_cell_proximities) > 0 & sample != "20210906_FOV3_D3"){
        interaction_celltypes <- rbind(interaction_celltypes,
                                       data.frame(cur_cell_proximities[cur_cell_proximities$unified_int %in% interactions,], 
                                                  experiment = strsplit(sample, split = "_")[[1]][1], fov = strsplit(sample, split = "_")[[1]][2], condition = strsplit(sample, split = "_")[[1]][3]))
      }
    }
    interaction_celltypes$p.adj <- ifelse(interaction_celltypes$enrichm > 0, interaction_celltypes$p.adj_higher, interaction_celltypes$p.adj_lower)


    
    sig_label <- as.character(ifelse(interaction_celltypes$p.adj < 0.1, paste0("*"), ""))

    g_test <- ggplot(interaction_celltypes, aes(x = condition, y = enrichm, fill = condition)) +
      geom_bar(stat = "identity", position = position_dodge2(width=0.9, preserve = "single")) +
      facet_grid(.~condition, scales = "free_x") +
      geom_text(aes(label=sig_label), position=position_dodge2(width=0.9, preserve = "single"), angle = 90, hjust = -0.02, size = 4) +
      ylim(-2,3.5)+
      NoLegend()+
      theme_classic2()+
      scale_fill_manual(values = cols_fov, name = "") +
      theme(axis.text.x = element_text(#angle = 50,
                                       vjust = 1, size = 12, hjust = 0.5, face = "bold"
                                       ),
            axis.text.y = element_text(hjust = 0.5, size = 12),
            axis.title.x = element_blank(),
            axis.title.y = element_text(size = 12),
            plot.title = element_text(size =14, hjust = 0.5),
            plot.margin = margin(0, 0.5, 0.5, 0.5, "cm"),
            legend.position = "none",
            strip.background=element_blank(),
            strip.background.x= element_blank(),
            strip.text.x = element_text(size = 1, color = "white"),
            panel.grid.major.y = element_line())+
      NoLegend()+  
      ggtitle(gsub("LYVE1 CD90 |EMCN CD31 |NK cells/ILC1s--|--NK cells/ILC1s", "", interactions)) +
      ylab("Enrichment")
    
    
    g_master_list[[unic]] <- g_test+
        theme(plot.margin = margin(0, 0.5, 0, 0.5, "cm"))
  }
}

# ILC2s around ILC2s -----------------------------------------
interactions <- c("NK cells/ILC1s--NK cells/ILC1s")
unic <- "NK cells/ILC1s"
background_image <- backgroundlist[["NK cells/ILC1s"]]
interaction_celltypes <- NULL
for(samp in vr_list_names){
    cur_cell_proximities <- cell_proximities_list[[samp]]
    cur_cell_proximities <- cur_cell_proximities[cur_cell_proximities$unified_int %in% interactions,]
    sample <- unique(metadatax$FullInfo[metadatax$Sample==samp])
    if(nrow(cur_cell_proximities) > 0 & sample != "20210906_FOV3_D3"){
      interaction_celltypes <- rbind(interaction_celltypes,
                                     data.frame(cur_cell_proximities[cur_cell_proximities$unified_int %in% interactions,], 
                                                experiment = strsplit(sample, split = "_")[[1]][1], fov = strsplit(sample, split = "_")[[1]][2], condition = strsplit(sample, split = "_")[[1]][3]))
    }
  }
interaction_celltypes$p.adj <- ifelse(interaction_celltypes$enrichm > 0, interaction_celltypes$p.adj_higher, interaction_celltypes$p.adj_lower)
  # plot test results
  # sig_label <- as.character(ifelse(interaction_celltypes$p.adj < 0.1, paste0("p=",round(interaction_celltypes$p.adj,3)), ""))
  sig_label <- as.character(ifelse(interaction_celltypes$p.adj < 0.1, paste0("*"), ""))
    # print(sig_label)
g_test <- ggplot(interaction_celltypes, aes(x = condition, y = enrichm, fill = condition)) +
  geom_bar(stat = "identity", position = position_dodge2(width=0.9, preserve = "single")) +
  facet_grid(.~condition, scales = "free_x") +
  geom_text(aes(label=sig_label), position=position_dodge2(width=0.9, preserve = "single"), angle = 90, hjust = -0.02, size = 4) +
  ylim(-2,3.5)+
  NoLegend()+
  theme_classic2()+
  scale_fill_manual(values = cols_fov, name = "") +
  theme(axis.text.x = element_text(#angle = 50,
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"
                                   ),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        plot.margin = margin(0, 0.5, 0.5, 0.5, "cm"),
        legend.position = "none",
        strip.background=element_blank(),
        strip.background.x= element_blank(),
        strip.text.x = element_text(size = 1, color = "white"),
        panel.grid.major.y = element_line())+
  NoLegend()+  
      ggtitle(gsub("LYVE1 CD90 |EMCN CD31 |NK cells/ILC1s--|--NK cells/ILC1s", "", interactions)) +
  ylab("Enrichment")


g_master_list[[unic]] <- g_test+
    theme(plot.margin = margin(0, 0.5, 0, 0.5, "cm"))

```

# Visualization

Co-enrichment analysis of NK cells/ILC1s

```{r, fig.width=9, fig.height=6}
enrichment_scores_all <- ggarrange(plotlist = g_master_list[c(1:9)], ncol = 4, nrow = 2, 
          labels = c("D"))

enrichment_scores_all
```

## NK cells/ILC1s localize close to vessels

### IF overlays

```{r}
set_ptsize <- 3
cell_shape <- 18
set_alpha <- 1

```

```{r, fig.width=4.5, fig.height=4.5}

# define markers for the Overlay

# CYAN
marker1 <- "EMCN"
# MAGENTA
marker2 <- "CD31"
# YELLOW
marker3 <- "CD90"
# GREEN
marker4 <- "EpCAM"
# RED
marker5 <- "CD90"

# define cell type of interested that should be plotted on the overlay
celltype_of_interest <- "NK cells/ILC1s"

ColorsCellTypeSingle <-  list(
  #`NK cells/ILC1s/ILC3s` = "cyan", 
  `NK cells/ILC1s` = "orange",
  #`ILC3s` = "magenta", 
  `EMCN CD31 Blood vessels` = "green")


name_channel_key <- paste0(marker1, "-c_", marker2, "-m_", marker3, "-y_", 
                           marker4, "-g_"
                           # marker5, "-r" 
                           )
vr_merged <- combineChannels(vr_merged,
                             channels = c(marker1, marker2, marker3, 
                                          marker4
                                          # marker5
                                          ),
                             colors = c("cyan", "magenta", "yellow" ,
                                        "green"
                                        # "red"
                                        ),
                             channel_key = name_channel_key)



celltype_of_interest <- "NK cells/ILC1s"

# CTRL ------------------------------------------------------------
plot <- vrSpatialPlot(vr_merged, assay = paste0("Assay", 2), 
                        group.by = "CellType", 
                        group.ids = celltype_of_interest,
                        alpha = set_alpha, 
                        background = c("image_1", name_channel_key), 
                        pt.size = set_ptsize, cell.shape = cell_shape)+
  guides(color = guide_legend(override.aes = list(size = 5)))+
  scale_color_manual(values = ColorsCellTypeSingle)+
  scale_fill_manual(values = ColorsCellTypeSingle)+
  theme_void()+ NoLegend()+ ggtitle(NULL)+
  ggtitle("CTRL")+
  theme(plot.title = element_text(hjust = 0.5, size = 14), 
        text = element_text(size = 12))



plot_if_ctrl <- plot +
  annotate("text", x=100, y=950, label= marker1,
           col="cyan", size=5, parse=TRUE) +
  annotate("text", x=90, y=880, label= marker2,
           col="magenta", size=5, parse=TRUE) +
  annotate("text", x=90, y=810, label= marker3,
           col="yellow", size=5, parse=TRUE)+
  annotate("text", x=110, y=740, label= marker4,
           col="green", size=5, parse=TRUE)+
  # annotate("text", x=70, y=920, label= marker5,
  #          col="red", size=3.5, parse=TRUE)+
  annotate("segment", x = 680, xend = 985, y = 45, yend = 45, size = 1.6, 
  colour = "white")

plot_if_ctrl


# IL-33 D3 ------------------------------------------------------------
plot <- vrSpatialPlot(vr_merged, assay = paste0("Assay", 35), #2
                        group.by = "CellType", 
                        group.ids = celltype_of_interest,
                        alpha = set_alpha, 
                        background = c("image_1", name_channel_key), 
                        pt.size = set_ptsize, cell.shape = cell_shape)+
  guides(color = guide_legend(override.aes = list(size = 5)))+
  scale_color_manual(values = ColorsCellTypeSingle)+
  scale_fill_manual(values = ColorsCellTypeSingle)+
  theme_void()+ NoLegend()+ ggtitle(NULL)+
  ggtitle("IL-33 day 3")+
  theme(plot.title = element_text(hjust = 0.5, size = 14), 
        text = element_text(size = 12))



plot_if_d3 <- plot +
  annotate("text", x=100, y=950, label= marker1,
           col="cyan", size=5, parse=TRUE) +
  annotate("text", x=90, y=880, label= marker2,
           col="magenta", size=5, parse=TRUE) +
  annotate("text", x=90, y=810, label= marker3,
           col="yellow", size=5, parse=TRUE)+
  annotate("text", x=110, y=740, label= marker4,
           col="green", size=5, parse=TRUE)+
  # annotate("text", x=70, y=920, label= marker5,
  #          col="red", size=3.5, parse=TRUE)+
  annotate("segment", x = 680, xend = 985, y = 45, yend = 45, size = 1.6, 
  colour = "white")

plot_if_d3
```

combine both plots:

```{r}
plot_if <- ggarrange(plot_if_ctrl, plot_if_d3, ncol = 2, labels = c("D", ""))
plot_if
```

### Coenrichment plot

```{r}

# fine tune the co-enrichment plot
# ILC2s around ILC2s -----------------------------------------
interactions <- c("EMCN CD31 Blood vessels--NK cells/ILC1s")
unic <- "EMCN CD31 Blood vessels"
background_image <- backgroundlist[["EMCN CD31 Blood vessels"]]
interaction_celltypes <- NULL
for(samp in vr_list_names){
    cur_cell_proximities <- cell_proximities_list[[samp]]
    cur_cell_proximities <- cur_cell_proximities[cur_cell_proximities$unified_int %in% interactions,]
    sample <- unique(metadatax$FullInfo[metadatax$Sample==samp])
    if(nrow(cur_cell_proximities) > 0 & sample != "20210906_FOV3_D3"){
      interaction_celltypes <- rbind(interaction_celltypes,
                                     data.frame(cur_cell_proximities[cur_cell_proximities$unified_int %in% interactions,], 
                                                experiment = strsplit(sample, split = "_")[[1]][1], fov = strsplit(sample, split = "_")[[1]][2], condition = strsplit(sample, split = "_")[[1]][3]))
    }
  }
interaction_celltypes$p.adj <- ifelse(interaction_celltypes$enrichm > 0, interaction_celltypes$p.adj_higher, interaction_celltypes$p.adj_lower)
  # plot test results
  # sig_label <- as.character(ifelse(interaction_celltypes$p.adj < 0.1, paste0("p=",round(interaction_celltypes$p.adj,3)), ""))
  sig_label <- as.character(ifelse(interaction_celltypes$p.adj < 0.1, paste0("*"), ""))
    # print(sig_label)
plot_coenrichment <- ggplot(interaction_celltypes, aes(x = condition, y = enrichm, fill = condition)) +
  geom_bar(stat = "identity", position = position_dodge2(width=0.9, preserve = "single")) +
  facet_grid(.~condition, scales = "free_x") +
  geom_text(aes(label=sig_label), position=position_dodge2(width=0.9, preserve = "single"), angle = 90, hjust = -0.02, size = 4) +
  ylim(-0.5,1.6)+
  NoLegend()+
  theme_classic2()+
  scale_fill_manual(values = cols_fov, name = "") +
  ggtitle(gsub("EMCN CD31 ", "", interactions)) +
  theme(axis.text.x = element_text(#angle = 50,
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"
                                   ),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        legend.position = "none",
        strip.background=element_blank(),
        strip.background.x= element_blank(),
        strip.text.x = element_text(size = 1, color = "white"),
        panel.grid.major.y = element_line())+
  NoLegend()+  
  ylab("Enrichment")

plot_coenrichment
```

### Minimum distance plot

```{r, fig.width=6, fig.height=4}
set.seed(8)
radius <- 10
unit <- "\u03BC"
thresh <- 0.04
nmarkers <- 33
save_name <- "SPIAT_cin_"

cols_nat <- c("magenta", "cyan", "blue", "purple", "green", 
                       "red", "yellow", "olivedrab1", "slateblue1", 
                       "darkcyan", "seagreen", "deeppink", 
                       "orange", "brown", "violet",
                       "deeppink4", "pink", 
                       "grey", "black", "lightgreen", 
                       "#FF0066", "gold", 
                       "lightblue", "#FFCC99", "#CC00FF", 
                       "blueviolet",  "goldenrod4", 
                       "indianred1", "navy", "olivedrab", "lightcyan", "seagreen2", "darkviolet", "lightpink", "slateblue4", "olivedrab2")
                


ColorsCellType <-  list(`NK cells/ILC1s` = "darkcyan", 
                        `ILC2s` = "seagreen2", 
                        `ILC3s` = "darkmagenta", 
                        `T helper cells` = "deeppink",
                        `T cytotox cells` = "slateblue", 
                        `Myeloid cells` = "gold", 
                        `B cells & Plasma cells` = "indianred1",
                        `LYVE1 CD31 vessels` = "darkgreen", 
                        `LYVE1 CD90 Lymphatics` = "yellow", 
                        `EMCN CD31 Blood vessels` = "red", 
                        `Epithelia` = "green")
ColorsCellType 

cols_treat <- c("darkcyan", "gold", "deeppink", "slateblue")

celltypes <- c(
  "NK cells/ILC1s", 
  "ILC2s", 
  "ILC3s", 
  "T helper cells", 
  "T cytotox cells", 
  "Myeloid cells", 
  "B cells & Plasma cells", 
  "LYVE1 CD31 vessels", 
  "LYVE1 CD90 Lymphatics", 
  "EMCN CD31 Blood vessels", 
  "Epithelia"
)

input_dir <- "C:/Users/NieHau/Desktop/Sandy/R/R_analysis_output/Niche_analysis_SPIAT_lung/Output_SPIAT/cells_in_neighborhood/"

list_files <- list.files(path=input_dir, 
                         pattern=NULL, all.files=FALSE,
                         full.names=FALSE)

df_cin = data.frame()
for (element in list_files) {
  dir <- paste0(input_dir, element)
  df_sub <- read_csv(dir, 
    col_types = cols(...1 = col_skip()))
  df_cin <- rbind(df_cin, df_sub)
}

df_cin$Experiment <- str_sub(df_cin$Dataset,-8,-1)
df_cin$FOV <- str_sub(df_cin$Dataset,-10,-10)  
df_cin$Treatment <- gsub("D", "", str_extract(df_cin$Dataset, "[^_]+"))
df_cin$ExpID <- paste0(df_cin$Experiment, "_", df_cin$FOV)
colnames(df_cin) <- gsub("Reference cell", "Reference", colnames(df_cin))
# colnames(df_cin) <- gsub("NK cells & ILC1s", "NK cells/ILC1s", colnames(df_cin))
# df_cin$Reference <- gsub("NK cells & ILC1s", "NK cells/ILC1s", df_cin$Reference)
head(df_cin)

# get the meta data of the treatment from the df_cin
df_treat <- cbind(df_cin["ExpID"], df_cin["Treatment"])
df_treat <- df_treat[!duplicated(df_treat), ]
head(df_treat)


input_dir <- "C:/Users/NieHau/Desktop/Sandy/R/R_analysis_output/Niche_analysis_SPIAT_lung/Output_SPIAT/cell_distances_minimal_all/"

list_files <- list.files(path=input_dir, 
                         pattern=NULL, all.files=FALSE,
                         full.names=FALSE)

df_dist = data.frame()
for (element in list_files) {
  dir <- paste0(input_dir, element)
  df_sub <- read_csv(dir, 
    col_types = cols(...1 = col_skip()))
  df_sub$Name <- element
  df_dist <- rbind(df_dist, df_sub)
}


head(df_dist)
df_dist$ExpID <- str_sub(df_dist$Name,7,16)
df_dist$Experiment <- str_sub(df_dist$Name,7,14)
df_dist$FOV <- str_sub(df_dist$Name,16,16)  

df_dist <- merge(df_dist, df_treat, 
                 by = "ExpID", 
                 all.x = TRUE) 

df_dist <- df_dist %>%
  mutate(Pair = paste(RefType, "--", NearestType))


df_dist$RefType <- gsub("NK cells & ILC1s", "NK cells/ILC1s", df_dist$RefType)
df_dist$NearestType <- gsub("NK cells & ILC1s", "NK cells/ILC1s", df_dist$NearestType)

df_dist$RefType <- factor(df_dist$RefType, levels = celltypes)
df_dist$NearestType <- factor(df_dist$NearestType, levels = celltypes)




df_dist_all <- df_dist

head(df_dist)



# filter condition and reference cell types to compare ILC subtypes and 
# T cells
df_dist_ref <- df_dist_all %>%
  # filter(Treatment == condition) %>%
  filter(RefType == "ILC2s"
         |
           RefType == "NK cells/ILC1s"| RefType == "ILC3s"|
           RefType == "T helper cells"| RefType == "T cytotox cells"| RefType == "Myeloid cells"| RefType == "B cells & Plasma cells"
         )

unique(df_dist_ref$Treatment)
df_dist_ref$Treatment <- factor(df_dist_ref$Treatment, levels = c(
  "CTRL", "1", "2", "3"
))
unique(df_dist_ref$RefType)


# LYMPHATICS ------------------------------------------------------------
celltype_of_interest <- "EMCN CD31 Blood vessels"
ypos <- 100


my_plot_list <- list()

celltype_of_interest <- "EMCN CD31 Blood vessels"

for (condition in c("CTRL", "1", "2", "3")) {
  
  plot_data <- df_dist_ref %>%
    filter(Treatment == condition) %>%
    filter(NearestType == celltype_of_interest)
  
  # Test for statistical significance of ILC2s to the other cell types
  stat.test <- plot_data %>%
    dunn_test(Distance ~ RefType) %>%
    adjust_pvalue(method = "bonferroni") %>%
    add_significance()
  stat.test <- stat.test %>% add_xy_position(x = "RefType")
  
  stat.test <- stat.test %>%
    filter(group1 == "NK cells/ILC1s"|group2 == "NK cells/ILC1s"
           )
  
  # Create lav´bels that depict mean value 
  Labs = plot_data %>% 
    group_by(RefType) %>%
    summarise(lab_text = paste0(round(median(Distance), 0), " µm"), lab_pos = quantile(Distance)[3]
                )
  
  # create plot
  plot <- ggplot(plot_data, aes(x=RefType , 
            y = Distance, 
            fill = "RefType")) +
    geom_boxplot(fill="white", outliers = FALSE)+
    geom_beeswarm(aes(color = RefType), alpha = 0.5, size = 0.1, cex = 0.1)+
    stat_pvalue_manual(stat.test,
                       size = 6,
                       hide.ns = TRUE, y.position = 200, step.increase = 0.1
                       )+
    scale_y_continuous(expand = c(0, 0), limits = c(0,320))+
    rotate_x_text(angle = 45)+
  ggtitle(gsub("3", "IL-33 day 3", condition))+
  scale_color_manual(values = ColorsCellType)+
  theme_classic2()+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, 
                                   # vjust = 1, hjust = 0.5, 
                                   size = 12, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        # axis.title.x = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        plot.margin = margin(0.5, 0, 0.5, 1, "cm"),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
    NoLegend()+
    xlab("Cell types")+
    ylab("Minimal distance [µm]")+
    geom_text(aes(y = 150, #lab_pos, 
                  label = lab_text, vjust = -0.5, hjst = 1), angle = 90,
              data = Labs,size=3)
  plot
  
  assigned_name <- gsub(" ", "", paste0(celltype_of_interest, "_", condition))
  assign(assigned_name, plot )
  my_plot_list[[assigned_name]] <- plot

}

ggarrange(plotlist = my_plot_list[c(1:4)], nrow = 1, ncol = 2)

dist_lymph <- ggarrange(plotlist = my_plot_list[c(1, 4)], nrow = 1, ncol = 2, labels = c("B", "C"))

dist_lymph

```

### CIN plot

```{r, fig.height=3, fig.width=9}

library(stringr)

input_dir <- "C:/Users/NieHau/Desktop/Sandy/R/R_analysis_output/Niche_analysis_SPIAT_all_organs_CIN/Output/"

# List all radii calculated 
list_files_rad <- list.files(path="C:/Users/NieHau/Desktop/Sandy/R/R_analysis_output/Niche_analysis_SPIAT_all_organs_CIN/Output/Lung", 
                         pattern=NULL, all.files=FALSE,
                         full.names=FALSE)

list_files_rad


df_cin_lung = data.frame()

tissuearea <- "Lung"

# define a dataframe to collect all data from one tissue area
df_radius <- data.frame()
for (defined_radius in list_files_rad) {
  print(defined_radius)
  list_files <- list.files(path=paste0(input_dir,
                                   tissuearea, 
                                   "/", 
                                   defined_radius, 
                                   "/"), 
                       pattern=NULL, all.files=FALSE,
                       full.names=FALSE)
  # define a dataframe to collect the data for all datasets of one 
  df_cin = data.frame()
  for (element in list_files) {
    dir <- paste0(input_dir,
                  tissuearea, 
                  "/", defined_radius, 
                  "/", element)
    df_sub <- read_csv(dir, 
      col_types = cols(...1 = col_skip()))
    df_sub$Filename <- paste0(tissuearea, 
                  "/", defined_radius, 
                  "/", element)
    df_cin <- rbind(df_cin, df_sub)
  }

  df_cin$Radius <- defined_radius
  df_radius <- rbind(df_radius, df_cin)
}

# collect data from current tissue area to datafram df_all_cin
df_cin_lung <- df_radius
df_cin_lung$Radius <- gsub("_micm", " \u03BCm", df_cin_lung$Radius)
df_cin_lung$Experiment <- str_sub(df_cin_lung$Dataset,-8,-1)
df_cin_lung$FOV <- str_sub(df_cin_lung$Dataset,-10,-10)  
df_cin_lung$Treatment <- str_extract(df_cin_lung$Dataset, "[^_]+")
df_cin_lung$ExpID <- paste0(df_cin_lung$Experiment, "_", df_cin_lung$FOV)
colnames(df_cin_lung) <- gsub("Reference cell", "Reference", 
                                colnames(df_cin_lung))

colnames(df_cin_lung) <- gsub("NK cells & ILC1s", "NK cells/ILC1s", 
                              colnames(df_cin_lung))
df_cin_lung$Reference <- gsub("NK cells & ILC1s", "NK cells/ILC1s",
                              df_cin_lung$Reference)
head(df_cin_lung)
colnames(df_cin_lung)
df_cin_lung$Treatment <- gsub("D", "", df_cin_lung$Treatment)

radius <- unique(df_cin_lung$Radius)[2]
celltype_of_interest <- "NK cells/ILC1s"

df_sub_lung <- df_cin_lung %>%
  filter(Reference == celltype_of_interest) %>%
  filter(Radius == radius) %>%
  select(Reference, Radius, Treatment, Dataset, `EMCN CD31 Blood vessels`, Tissue.area)

head(df_sub_lung)



plot_data <- df_sub_lung

# Create lav´bels that depict mean value 
Labs = plot_data %>% 
  group_by(Treatment) %>%
  summarise(lab_text = paste0(round(median(`EMCN CD31 Blood vessels`), 0), " %"), lab_pos = quantile(`EMCN CD31 Blood vessels`)[3]+2
              )

plot_data$Treatment <- factor(plot_data$Treatment, levels = c("CTRL", "1", "2", "3"))
# create plot
plot_cin <- ggplot(plot_data, aes(x = Treatment, y = `EMCN CD31 Blood vessels`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(axis.text.x = element_text(#angle = 50,
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  NoLegend()+
  ggtitle("Blood vessels")+
  xlab("Treatment")+
  ylab("Frequency in\n15 µm radius [%]")+
  # scale_y_continuous(expand = c(0, 0), limits = c(10,40))+
  geom_text(aes(y = lab_pos, label = lab_text, vjust = -0.5), data = Labs,size=3)
plot_cin
```

For comparison, check the CIN of :

```{r, fig.height=3, fig.width=9}

# B cells ------------------------------------------------------------
celltype_of_interest <- "B cells & Plasma cells"

df_sub_lung <- df_cin_lung %>%
  filter(Reference == celltype_of_interest) %>%
  filter(Radius == radius) %>%
  select(Reference, Radius, Treatment, Dataset, `EMCN CD31 Blood vessels`, Tissue.area)

head(df_sub_lung)



plot_data <- df_sub_lung

# Create lav´bels that depict mean value 
Labs = plot_data %>% 
  group_by(Treatment) %>%
  summarise(lab_text = paste0(round(median(`EMCN CD31 Blood vessels`), 0), " %"), lab_pos = quantile(`EMCN CD31 Blood vessels`)[3]+2
              )

plot_data$Treatment <- factor(plot_data$Treatment, levels = c("CTRL", "1", "2", "3"))
# create plot
ggplot(plot_data, aes(x = Treatment, y = `EMCN CD31 Blood vessels`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(axis.text.x = element_text(#angle = 50,
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  NoLegend()+
  ggtitle("B cells & Plasma cells - EMCN CD31 Blood vessels")+
  xlab("Treatment")+
  ylab("Frequency in 15 µm radius [%]")+
  # scale_y_continuous(expand = c(0, 0), limits = c(10,40))+
  geom_text(aes(y = lab_pos, label = lab_text, vjust = -0.5), data = Labs,size=3)

# T cells ---------------------------------------------------------------
celltype_of_interest <- "T helper cells"

df_sub_lung <- df_cin_lung %>%
  filter(Reference == celltype_of_interest) %>%
  filter(Radius == radius) %>%
  select(Reference, Radius, Treatment, Dataset, `EMCN CD31 Blood vessels`, Tissue.area)

head(df_sub_lung)



plot_data <- df_sub_lung

# Create lav´bels that depict mean value 
Labs = plot_data %>% 
  group_by(Treatment) %>%
  summarise(lab_text = paste0(round(median(`EMCN CD31 Blood vessels`), 0), " %"), lab_pos = quantile(`EMCN CD31 Blood vessels`)[3]+2
              )

plot_data$Treatment <- factor(plot_data$Treatment, levels = c("CTRL", "1", "2", "3"))
# create plot
ggplot(plot_data, aes(x = Treatment, y = `EMCN CD31 Blood vessels`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(axis.text.x = element_text(#angle = 50,
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  NoLegend()+
  ggtitle("T helper cells - EMCN CD31 Blood vessels")+
  xlab("Treatment")+
  ylab("Frequency in 15 µm radius [%]")+
  # scale_y_continuous(expand = c(0, 0), limits = c(10,40))+
  geom_text(aes(y = lab_pos, label = lab_text, vjust = -0.5), data = Labs,size=3)

# T cells ---------------------------------------------------------------
celltype_of_interest <- "Myeloid cells"

df_sub_lung <- df_cin_lung %>%
  filter(Reference == celltype_of_interest) %>%
  filter(Radius == radius) %>%
  select(Reference, Radius, Treatment, Dataset, `EMCN CD31 Blood vessels`, Tissue.area)

head(df_sub_lung)



plot_data <- df_sub_lung

# Create lav´bels that depict mean value 
Labs = plot_data %>% 
  group_by(Treatment) %>%
  summarise(lab_text = paste0(round(median(`EMCN CD31 Blood vessels`), 0), " %"), lab_pos = quantile(`EMCN CD31 Blood vessels`)[3]+2
              )

plot_data$Treatment <- factor(plot_data$Treatment, levels = c("CTRL", "1", "2", "3"))
# create plot
ggplot(plot_data, aes(x = Treatment, y = `EMCN CD31 Blood vessels`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(axis.text.x = element_text(#angle = 50,
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  NoLegend()+
  ggtitle("Myeloid cells - EMCN CD31 Blood vessels")+
  xlab("Treatment")+
  ylab("Frequency in 15 µm radius [%]")+
  # scale_y_continuous(expand = c(0, 0), limits = c(10,40))+
  geom_text(aes(y = lab_pos, label = lab_text, vjust = -0.5), data = Labs,size=3)

# T cells ---------------------------------------------------------------
celltype_of_interest <- "T cytotox cells"

df_sub_lung <- df_cin_lung %>%
  filter(Reference == celltype_of_interest) %>%
  filter(Radius == radius) %>%
  select(Reference, Radius, Treatment, Dataset, `EMCN CD31 Blood vessels`, Tissue.area)

head(df_sub_lung)



plot_data <- df_sub_lung

# Create lav´bels that depict mean value 
Labs = plot_data %>% 
  group_by(Treatment) %>%
  summarise(lab_text = paste0(round(median(`EMCN CD31 Blood vessels`), 0), " %"), lab_pos = quantile(`EMCN CD31 Blood vessels`)[3]+2
              )

plot_data$Treatment <- factor(plot_data$Treatment, levels = c("CTRL", "1", "2", "3"))
# create plot
ggplot(plot_data, aes(x = Treatment, y = `EMCN CD31 Blood vessels`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(axis.text.x = element_text(#angle = 50,
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  NoLegend()+
  ggtitle("T cytotox cells - EMCN CD31 Blood vessels")+
  xlab("Treatment")+
  ylab("Frequency in 15 µm radius [%]")+
  # scale_y_continuous(expand = c(0, 0), limits = c(10,40))+
  geom_text(aes(y = lab_pos, label = lab_text, vjust = -0.5), data = Labs,size=3)


# Epithelia ---------------------------------------------------------------
celltype_of_interest <- "Epithelia"

df_sub_lung <- df_cin_lung %>%
  filter(Reference == celltype_of_interest) %>%
  filter(Radius == radius) %>%
  select(Reference, Radius, Treatment, Dataset, `EMCN CD31 Blood vessels`, Tissue.area)

head(df_sub_lung)



plot_data <- df_sub_lung

# Create lav´bels that depict mean value 
Labs = plot_data %>% 
  group_by(Treatment) %>%
  summarise(lab_text = paste0(round(median(`EMCN CD31 Blood vessels`), 0), " %"), lab_pos = quantile(`EMCN CD31 Blood vessels`)[3]+2
              )

plot_data$Treatment <- factor(plot_data$Treatment, levels = c("CTRL", "1", "2", "3"))
# create plot
ggplot(plot_data, aes(x = Treatment, y = `EMCN CD31 Blood vessels`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(axis.text.x = element_text(#angle = 50,
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  NoLegend()+
  ggtitle("Epithelia - EMCN CD31 Blood vessels")+
  xlab("Treatment")+
  ylab("Frequency in 15 µm radius [%]")+
  # scale_y_continuous(expand = c(0, 0), limits = c(10,40))+
  geom_text(aes(y = lab_pos, label = lab_text, vjust = -0.5), data = Labs,size=3)


# EMCN CD31 Blood vessels ---------------------------------------------------------------
celltype_of_interest <- "EMCN CD31 Blood vessels"

df_sub_lung <- df_cin_lung %>%
  filter(Reference == celltype_of_interest) %>%
  filter(Radius == radius) %>%
  select(Reference, Radius, Treatment, Dataset, `EMCN CD31 Blood vessels`, Tissue.area)

head(df_sub_lung)



plot_data <- df_sub_lung

# Create lav´bels that depict mean value 
Labs = plot_data %>% 
  group_by(Treatment) %>%
  summarise(lab_text = paste0(round(median(`EMCN CD31 Blood vessels`), 0), " %"), lab_pos = quantile(`EMCN CD31 Blood vessels`)[3]+2
              )

plot_data$Treatment <- factor(plot_data$Treatment, levels = c("CTRL", "1", "2", "3"))
# create plot
ggplot(plot_data, aes(x = Treatment, y = `EMCN CD31 Blood vessels`, fill = "Treatment"))+
  geom_boxplot(fill="white")+
  geom_beeswarm(aes(color = Treatment), size = 2, cex = 3)+
  scale_color_manual(values = cols_treat)+
  theme_classic2()+
  theme(axis.text.x = element_text(#angle = 50,
                                   vjust = 1, size = 12, hjust = 0.5, face = "bold"),
        axis.text.y = element_text(hjust = 0.5, size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size =14, hjust = 0.5),
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        legend.title = element_text(size =14),
        legend.text = element_text(size =12))+
  NoLegend()+
  ggtitle("EMCN CD31 Blood vessels - EMCN CD31 Blood vessels")+
  xlab("Treatment")+
  ylab("Frequency in 15 µm radius [%]")+
  # scale_y_continuous(expand = c(0, 0), limits = c(10,40))+
  geom_text(aes(y = lab_pos, label = lab_text, vjust = -0.5), data = Labs,size=3)

```

Combine plots:

```{r, fig.width=9, fig.height=9}
plot1 <- ggarrange(plot_coenrichment, dist_lymph,  
          ncol = 2, nrow = 1, widths = c(1.3, 2, 2),
          labels = c("A"))

ggarrange(plot1, plot_if,  
          ncol = 1, nrow = 2, height = c(1, 2))
```

## Session Information

```{r}
save.image(paste0(output_dir, "/environment.RData"))
sessionInfo()
```
