---
title: "Figure 3: Immune cells and ILCs in lung"
author: "Sandy Kroh"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    number_sections: yes
    fig_caption: yes
    keep_md: yes
  pdf_document:
    toc: yes
params:
  Sample: Default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", 
                      fig.align='center', dpi = 600, 
                      message = FALSE, warning = FALSE)
options(width = 1200)
```

## Libraries

```{r}
library(Seurat)
library(SeuratObject)
library(dplyr)
library(ggplot2)
# library(stringr)
# library(glue)
# library(here)
library(readr)
# library(lubridate)
# library(data.table)
# library(clustree)
# library(magrittr)
library(ggpubr)
# library(ggrepel)
# library(readxl)
# library(openxlsx)
```

## Parameters

```{r}
set.seed(123)

input_dir <- here::here("1_data_tidying", "Lung_SI_all_cells_all_ALs_files")

output_dir <- here::here("2_visualizations_for_figures", "Supp_Fig_1_AL2_in_lung_files")
dir.create(output_dir)




main_markers <- c(
  "EpCAM", "EMCN", "LYVE1", "PDPN", "PDGFRa", "CD8a", "CD4",
  "CD45", "CD3", "IRF4", "Kappa", "CD11c", "CD127", "GATA3eGFP", "RORgt"
)


immune_markers <- c(
 "CD3", "CD4", "CD8a", "Kappa", "IRF4", "CD11c",
  "CD127", "CD90", "EOMES", "GATA3eGFP", "RORgt", "Ki67",  "KLRG1", "NKp46", "CD117", "Areg", "CCR6", "CD44", "MHCII", "Sca1"
)

ilc_markers <- c(
  "CD3", "CD4", "CD8a",
  "CD127", "CD90", "EOMES", "GATA3eGFP", "RORgt", "KLRG1", "NKp46", "CD117", "CCR6", "MHCII", "Ki67", "Areg", "IRF4", "Sca1", "CD44"
)


cols_nat <- c("magenta", "cyan", "blue", "purple", "green", 
                       "red", "yellow", "olivedrab1", "slateblue1", 
                       "darkcyan", "gold","indianred1", "seagreen", "deeppink", 
                       "orange", "brown", "violet",
                       "deeppink4", "pink", 
                       "grey", "black", "lightgreen", 
                       "#FF0066",  
                       "lightblue", "#FFCC99", "#CC00FF", 
                       "blueviolet",  "goldenrod4", 
                       "navy", "olivedrab", "lightcyan", "seagreen2", "darkviolet", "lightpink", "slateblue4", "olivedrab2")

colfunc <- colorRampPalette(c("darkcyan", "green", "yellow", "magenta", "purple"))

```

# Load data

```{r, fig.width=9, fig.height=6}

SO.lung <- readRDS(paste0(input_dir, "/lung_all_cells_all_ALs.rds"))
dim(SO.lung)

SO.lung$AL1 <- gsub("Vessels", "Stromal cells", SO.lung$AL1)
SO.lung$AL2 <- gsub("LYVE1 CD90 |EMCN CD31 ", "", SO.lung$AL2)
SO.lung$AL2 <- gsub("LYVE1 CD31 vessels", "CD45- IRF4+ cells", SO.lung$AL2)
SO.lung$AL3 <- gsub("LYVE1 CD31 vessels", "CD45- IRF4+ cells", SO.lung$AL3)
```

# Visualization

## Dotplot AL2

```{r, fig.width=9, fig.height=3}

SO.lung$AL2 <- factor(SO.lung$AL2, levels = c(
  "Epithelia",
  "Blood vessels",
  "Lymphatics",
  "CD45- IRF4+ cells", 
  "Myeloid cells", 
  "B cells & Plasma cells", 
  "ILCs", 
  "T cytotox. cells", 
  "T helper cells"
  ))


dot_plot <- Seurat::DotPlot(subset(SO.lung, subset = AL1 != "Immune cells"), 
                group.by = "AL2",
                  features = c(
                    "CD45", 
                    "IRF4", 
                    "Kappa",
                    "PDGFRa", 
                    "LYVE1",
                    "CD90", 
                    "PDPN", 
                    "Sca1", 
                    "CD31", 
                    "EMCN", 
                    "CD117",
                    "EpCAM", 
                    "CD138"
                  ), 
                cols ="RdBu", assay = "MELC")+   
    RotatedAxis()+
    # coord_flip()+
    theme(axis.text.x=element_text(size=12, angle = 45),
          axis.text.y=element_text(size=14), 
          plot.margin = margin(2, 0, 0.4, 0.5, "cm"), 
          axis.title.y = element_blank(), 
          plot.title = element_blank())+ 
  scale_color_gradient2(midpoint = 0, low = "gold", 
                            high = "blue", space = "Lab" )

dot_plot
```

```{r, fig.width=9, fig.height=4.5}

SO.lung$AL3 <- factor(SO.lung$AL3, levels = c(
  "Epithelia",
  "CD45- IRF4+ cells",
  "Lymphatics",
  "Blood vessels", 
  "Myeloid cells", 
  "B cells & Plasma cells", 
  "T cytotox cells", 
  "T helper cells", 
  "ILC3s", 
  "ILC2s", 
  "NK cells/ILC1s"
))


dot_plot <- Seurat::DotPlot(SO.lung, 
                group.by = "AL3",
                  features = c(
                    "CD45", 
                    "EOMES", 
                    "TBET", 
                    "GATA3eGFP", 
                    "KLRG1", 
                    "ICOS",
                    "RORgt",
                    "CD4", 
                    "CD3", 
                    "CD8a", 
                    "B220", 
                    "Kappa",
                    "MHCII", 
                    "CD68", 
                    "CD11c",
                    "CD31", 
                    "EMCN", 
                    "CD117",
                    "CD90", 
                    "PDGFRa", 
                    "LYVE1",
                    "IRF4",
                    "EpCAM", 
                    "CD138" 
                  ), 
                cols ="RdBu", assay = "MELC")+   
    RotatedAxis()+
  ggtitle("All annotated cell types (AL3)")+
    # coord_flip()+
    theme(axis.text.x=element_text(size=12, angle = 45),
          axis.text.y=element_text(size=14), 
          plot.margin = margin(0.4, 0, 0.4, 0.5, "cm"), 
          axis.title.y = element_blank(), 
          plot.title = element_text(size=14, hjust = 0.5))+ 
  scale_color_gradient2(midpoint = 0, low = "gold", 
                            high = "blue", space = "Lab" )

dot_plot
```

```{r, fig.width=9, fig.height=5}

SO.lung$AL3 <- factor(SO.lung$AL3, levels = c(
  "Myeloid cells", 
  "B cells & Plasma cells", 
  "T cytotox cells", 
  "T helper cells", 
  "ILC3s", 
  "ILC2s", 
  "NK cells/ILC1s"
))


dot_plot <- Seurat::DotPlot(subset(SO.lung, subset = AL2 == "ILCs"), 
                group.by = "AL3",
                  features = c(
                    "NKp46", 
                    "CD117",
                    "EOMES", 
                    "TBET", 
                    "GATA3eGFP", 
                    "KLRG1", 
                    "ICOS", 
                    "RORgt",
                    "MHCII", 
                    "CD90", 
                    "CD127", 
                    "CD138" 
                  ), 
                cols ="RdBu", assay = "MELC", split.by = "Treatment")+   
    RotatedAxis()+
  ggtitle("ILC subtypes (AL3)")+
    # coord_flip()+
    theme(axis.text.x=element_text(size=12, angle = 45),
          axis.text.y=element_text(size=14), 
          plot.margin = margin(0.5, 1.5, 0.5, 1.5, "cm"), 
          axis.title.y = element_blank(), 
          plot.title = element_text(size=14, hjust = 0.5))+ 
  scale_color_gradient2(midpoint = 0, low = "green", mid = "gold",
                            high = "purple", space = "Lab" )+
  geom_hline(aes(yintercept=c(4.5)),
            color="black", size=0.2) + 
  geom_hline(aes(yintercept=c(8.5)),
            color="black", size=0.2)

dot_plot
```

## Session Information

```{r}
save.image(paste0(output_dir, "/environment.RData"))
sessionInfo()
```
