---
title: "Supplmentary Figure 3: immune and non-immune cell types SI"
author: "Sandy Kroh"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    number_sections: yes
    fig_caption: yes
    keep_md: yes
  pdf_document:
    toc: yes
params:
  Sample: Default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", 
                      fig.align='center', dpi = 600, 
                      message = FALSE, warning = FALSE)
options(width = 1200)
```

## Libraries

```{r}
library(Seurat)
library(SeuratObject)
library(dplyr)
library(ggplot2)
# library(stringr)
# library(glue)
# library(here)
library(readr)
# library(lubridate)
# library(data.table)
# library(clustree)
# library(magrittr)
library(ggpubr)
# library(ggrepel)
# library(readxl)
# library(openxlsx)
```

## Parameters

```{r}
set.seed(123)

input_dir <- here::here("1_data_tidying", "Lung_SI_all_cells_all_ALs_files")

output_dir <- here::here("2_visualizations_for_figures", "Supp_Fig_3_cell_type_annotation_SI_AL1_files")
dir.create(output_dir)




main_markers <- c(
  "EpCAM", "EMCN", "LYVE1", "PDPN", "PDGFRa", "CD8a", "CD4",
  "CD45", "CD3", "IRF4", "Kappa", "CD11c", "CD127", "GATA3eGFP", "RORgt"
)

immune_markers <- c(
 "CD3", "CD4", "CD8a", "Kappa", "IRF4", "CD11c",
  "CD127", "CD90", "EOMES", "GATA3eGFP", "RORgt", "Ki67",  "KLRG1", "NKp46", "CD117", "Areg", "CCR6", "CD44", "MHCII", "Sca1"
)

ilc_markers <- c(
  "CD3", "CD4", "CD8a",
  "CD127", "CD90", "EOMES", "GATA3eGFP", "RORgt", "KLRG1", "NKp46", "CD117", "CCR6", "MHCII", "Ki67", "Areg", "IRF4", "Sca1", "CD44"
)


cols_nat <- c("magenta", "cyan", "blue", "purple", "green", 
                       "red", "yellow", "olivedrab1", "slateblue1", 
                       "darkcyan", "gold","indianred1", "seagreen", "deeppink", 
                       "orange", "brown", "violet",
                       "deeppink4", "pink", 
                       "grey", "black", "lightgreen", 
                       "#FF0066",  
                       "lightblue", "#FFCC99", "#CC00FF", 
                       "blueviolet",  "goldenrod4", 
                       "navy", "olivedrab", "lightcyan", "seagreen2", "darkviolet", "lightpink", "slateblue4", "olivedrab2")

colfunc <- colorRampPalette(c("darkcyan", "green", "yellow", "magenta", "purple"))

```

# Load data

```{r, fig.width=9, fig.height=6}

SO.si <- readRDS(paste0(input_dir, "/si_all_cells_all_ALs.rds"))
dim(SO.si)

SO.si$AL1 <- gsub("Epithelia & stroma", "Epithelia", SO.si$AL1)
colnames(SO.si@meta.data)
```

# Visualization

## Dotplot AL1

```{r, fig.width=3, fig.height=7}

SO.si$AL1 <- factor(SO.si$AL1, levels = c("Immune cells", "Vessels & stroma", "Epithelia"))

dot_plot <- Seurat::DotPlot(SO.si, 
                group.by = "AL1",
                  features = c(
                    "CD11c", 
                    "CD3", 
                    "MHCII", 
                    "CD45", 
                    "CD90", 
                    "CD31", 
                    "LYVE1", 
                    "PDPN",
                    "Sca1",
                    "EMCN",
                    "EpCAM", 
                    "Ki67", 
                    "CD138"
                  ), 
                cols ="RdBu", assay = "MELC")+   
    RotatedAxis()+
    coord_flip()+
    theme(axis.text.x=element_text(size=12, angle = 45),
          axis.text.y=element_text(size=12), 
          legend.position = "right", 
          legend.text = element_text(size=8),
          legend.title = element_text(size=8),
          plot.margin = margin(1, 0.5, 8, 0, "cm"), 
          axis.title.x = element_blank(), 
          plot.title = element_blank())+ 
  scale_color_gradient2(midpoint = 0, low = "gold", 
                            high = "blue", space = "Lab" )

dot_plot
```

## Comparison annotation & IF overlay AL1

### Villi - Annotated cells of AL1:

```{r, fig.width=3, fig.height=3.9}


df_all_cells <- FetchData(SO.si, 
                        vars = c("Dataset",
                                 "Treatment",
                                 "AL1", 
                                 "CellID", 
                                 "Experiment", 
                                 "Location_Center_X", 
                                 "Location_Center_Y", 
                                 "UMAP_1", "UMAP_2"))


my_colors <- c("darkcyan", "deeppink", "gold")


df_fov <- df_all_cells %>%
          filter(Dataset == "CTRL_FOV1_20210730")

df_fov$AL1 <- factor(df_fov$AL1, 
                                       levels = c("Immune cells", "Vessels & stroma", "Epithelia"))
plot_ann_1 <- ggplot()+ 
  geom_point(data = df_fov, 
                       aes(x= Location_Center_X, y= Location_Center_Y, 
                           color = AL1), 
                      size = 0.5)+
    ggplot2::guides(color=guide_legend(override.aes = list(size=5), ncol=3), 
                    fill=guide_legend(ncol = 1,byrow=TRUE))+
  theme(legend.position = "bottom", 
          plot.margin=margin(0.5,1,0,1,"cm"),
          plot.title = element_text(size = 14, hjust = 0.5),
          text = element_blank(),
          axis.ticks = element_blank(),
          panel.grid =  element_blank(),
          legend.ticks = element_blank(),
          legend.title=element_blank(),
          legend.key = element_blank(),
          legend.text = element_text(size=14),
          panel.background = element_rect(fill = 'black', 
                                         color = 'black', size = 1))+  
  ggtitle("SI villi")+
    scale_colour_discrete(name  ="Annotated cell types",
                          breaks=c("Immune cells",
                                                  "Vessels & stroma",
                                                  "Epithelia"),
                          labels=c("Immune cells",
                                                  "Vessels & stroma",
                                                  "Epithelia")) +
    scale_color_manual(values = my_colors)+ 
    ggplot2::guides(color=guide_legend(override.aes = list(size=5), ncol=1),
                  fill=guide_legend(ncol = 1,byrow=TRUE))+
  xlim(0, 2048)+
  ylim(0, 2048) +
  scale_y_reverse()

plot_ann_1 <- ggarrange(plot_ann_1,
          nrow = 1, ncol = 1, 
          #widths = c(4.5, 4.5), 
          align = "v",
          font.label=list(size=12),hjust=-0.5
          )+    
  ggplot2::theme(legend.position = "left")+
  theme(plot.margin=margin(0,0,0,0,"cm"))
plot_ann_1
```

### Villi - IF overlay

```{r, fig.width=3, fig.height=3.1}
img <- png::readPNG(
    "D:/Sandy/Promotion/Dissertation/Figures/20210730_1_si_ctrl_CD45-c_CD31-m_EpCAM-y.png"
  )


my_colors <- c("cyan", "magenta", "yellow")

g <- grid::rasterGrob(img, interpolate=TRUE)



df_fov <- df_fov %>%
  mutate(AL1 = recode(
    AL1, 
    "Immune cells" = "CD45",
    "Vessels & stroma" = "CD31",
    "Epithelia" = "EpCAM"
  ))

plot_if_1 <- ggplot()+ 
  geom_point(data = df_fov, 
                       aes(x= Location_Center_X, y= Location_Center_Y, color = AL1), 
                       size = 1)+
  annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf)+
  theme(legend.title=element_blank())+ # exclude legend title
  scale_colour_discrete(name  ="MELC IF stainings",
                          breaks=c("CD45", "CD31", 
                                   "EpCAM"),
                          labels=c("CD45", "CD31", 
                                   "EpCAM")) +
  scale_color_manual(values = my_colors)+ 
    theme(legend.position = "bottom", 
          plot.margin=margin(0.5,1,0.5,1,"cm"),
          text = element_blank(),
           axis.ticks = element_blank(),
         panel.grid =  element_blank(),
          legend.ticks = element_blank(),
         legend.title=element_blank(),
         legend.key = element_blank(),
        legend.text = element_text(size=14), 
         panel.background = element_rect(fill = 'black', 
                                         color = 'black', size = 1))+    
  ggplot2::theme(legend.position = "bottom")+
  ggplot2::guides(color=guide_legend(override.aes = list(size=5), ncol=3),
                  fill=guide_legend(ncol = 3,byrow=TRUE))


plot_if_1 <- ggarrange(plot_if_1, 
            nrow = 1, ncol = 1, 
          #widths = c(4.5, 4.5), 
          align = "v",
          font.label=list(size=12),hjust=-0.5
          )+    
  ggplot2::theme(legend.position = "left")
  
plot_if_1
```

Combine plots:

```{r, fig.width=3, fig.height=7}
plot_villi <- ggarrange(plot_ann_1, plot_if_1, ncol = 1, nrow = 2, heights = c(3.5, 2.8), labels = c("B")
          )+
  theme(plot.margin = margin(0, 0, 0, 0, "cm"))

plot_villi
```

### ILF - Annotated cell types

```{r, fig.width=3, fig.height=3.9}

df_all_cells <- FetchData(SO.si, 
                        vars = c("Dataset",
                                 "Treatment",
                                 "AL1", 
                                 "CellID", 
                                 "Experiment", 
                                 "Location_Center_X", 
                                 "Location_Center_Y", 
                                 "UMAP_1", "UMAP_2"))


my_colors <- c("darkcyan", "deeppink", "gold")


df_fov <- df_all_cells %>%
          filter(Dataset == "CTRL_FOV1_20210810")

df_fov$AL1 <- factor(df_fov$AL1, 
                                       levels = c("Immune cells", "Vessels & stroma", "Epithelia"))
plot_ann_1_ilf <- ggplot()+ 
  geom_point(data = df_fov, 
                       aes(x= Location_Center_X, y= Location_Center_Y, 
                           color = AL1), 
                      size = 0.5)+
  ggplot2::guides(color=guide_legend(override.aes = list(size=5), ncol=3), 
                    fill=guide_legend(ncol = 1,byrow=TRUE))+
  theme(legend.position = "bottom", 
          plot.margin=margin(0.5,1,0,1,"cm"),
          plot.title = element_text(size = 14, hjust = 0.5),
          text = element_blank(),
          axis.ticks = element_blank(),
          panel.grid =  element_blank(),
          legend.ticks = element_blank(),
          legend.title=element_blank(),
          legend.key = element_blank(),
          legend.text = element_text(size=14),
          panel.background = element_rect(fill = 'black', 
                                         color = 'black', size = 1))+  
  ggtitle("SI ILF")+
  scale_colour_discrete(name  ="Annotated cell types",
                          breaks=c("Immune cells",
                                                  "Vessels & stroma",
                                                  "Epithelia"),
                          labels=c("Immune cells",
                                                  "Vessels & stroma",
                                                  "Epithelia")) +
  scale_color_manual(values = my_colors)+ 
  ggplot2::guides(color=guide_legend(override.aes = list(size=5), ncol=1),
                  fill=guide_legend(ncol = 1,byrow=TRUE))+
  xlim(0, 2048)+
  ylim(0, 2048) 

plot_ann_1_ilf <- ggarrange(plot_ann_1_ilf,
          nrow = 1, ncol = 1, 
          #widths = c(4.5, 4.5), 
          align = "v",
          font.label=list(size=12),hjust=-0.5
          )+    
  ggplot2::theme(legend.position = "left")+
  theme(plot.margin=margin(0,0,0,0,"cm"))
plot_ann_1_ilf
```

```{r, fig.width=3, fig.height=3.1}
img <- png::readPNG(
    "D:/Sandy/Promotion/Dissertation/Figures/20210810_1_si_ctrl_CD45-c_CD31-m_EpCAM-y.png"
  )


my_colors <- c("cyan", "magenta", "yellow")

g <- grid::rasterGrob(img, interpolate=TRUE)



df_fov <- df_fov %>%
  mutate(AL1 = recode(
    AL1, 
    "Immune cells" = "CD45",
    "Vessels & stroma" = "CD31",
    "Epithelia" = "EpCAM"
  ))

plot_if_ilf <- ggplot()+ 
  geom_point(data = df_fov, 
                       aes(x= Location_Center_X, y= Location_Center_Y, color = AL1), 
                       size = 1)+
  annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf)+
  theme(legend.title=element_blank())+ # exclude legend title
  scale_colour_discrete(name  ="MELC IF stainings",
                          breaks=c("CD45", "CD31", 
                                   "EpCAM"),
                          labels=c("CD45", "CD31", 
                                   "EpCAM")) +
  scale_color_manual(values = my_colors)+ 
    theme(legend.position = "bottom", 
          plot.margin=margin(0.5,1,0.5,1,"cm"),
          text = element_blank(),
           axis.ticks = element_blank(),
         panel.grid =  element_blank(),
          legend.ticks = element_blank(),
         legend.title=element_blank(),
         legend.key = element_blank(),
        legend.text = element_text(size=14), 
         panel.background = element_rect(fill = 'black', 
                                         color = 'black', size = 1))+    
  ggplot2::theme(legend.position = "bottom")+
  ggplot2::guides(color=guide_legend(override.aes = list(size=5), ncol=3),
                  fill=guide_legend(ncol = 3,byrow=TRUE))


plot_if_ilf <- ggarrange(plot_if_ilf, 
            nrow = 1, ncol = 1, 
          #widths = c(4.5, 4.5), 
          align = "v",
          font.label=list(size=12),hjust=-0.5
          )+    
  ggplot2::theme(legend.position = "left")
  
plot_if_ilf
```

Combine plots:

```{r, fig.width=3, fig.height=7}
plot_ilf <- ggarrange(plot_ann_1_ilf, plot_if_ilf, ncol = 1, nrow = 2, heights = c(3.5, 2.8), labels = c("")
          )+
  theme(plot.margin = margin(0, 0, 0, 0, "cm"))

plot_ilf
```

### Combine plots for figure

```{r, fig.width=9, fig.height=7}
ggarrange(dot_plot, plot_villi, plot_ilf, ncol = 3, nrow = 1, widths = c(3, 3, 3), labels = c("A"))+
  theme(plot.margin = margin(0, 0, 0, 0, "cm"))
```

## Session Information

```{r}
save.image(paste0(output_dir, "/environment.RData"))
sessionInfo()
```
